### ISSUE TITLE
[feat] 功能建议 CTRL+A 全选

### ISSUE THREAD

**Issue by wxyShine** [EcoPasteHub/EcoPaste#149]
### Describe the problem

![image](https://github.com/user-attachments/assets/d67cff62-dcb7-4bf3-bcfb-7c6a994382d2)
CTRL+A 全选

### Describe the solution you'd like

能否兼容CTRL+A 全选时  选中下面全部条目，当前好像时选中界面全部内容

**Comment by ayangweb** [comment]
收到反馈，你选中条目是想做什么操作呢？如果是删除的话，右键已经支持了删除全部的哦！

**Comment by wxyShine** [comment]
> 收到反馈，你选中条目是想做什么操作呢？如果是删除的话，右键已经支持了删除全部的哦！

好的  用ditto时 习惯 ctrl+a 后delete了。
这个给功能好处理的话感觉可以加上，ctrl+a这个快捷键在大部分软件中应该都是默认全选 挺方便

**Comment by ayangweb** [comment]
好的，这个可以看用户需求了来决定是否支持，暂时先用右键的删除全部代替！

**Comment by ayangweb** [comment]
Duplicate of #720 

如果有必要的话，后续会列入多选操作中！
