### ISSUE TITLE
[feat] 文件类型的展示优化

### ISSUE THREAD

**Issue by Half1900** [EcoPasteHub/EcoPaste#151]
### Describe the bug

第1次复制的文件会保留其链接并有大小，但是第2次在已有的第1次上选择复制时，只会复制其字面的文字，并不会把原本的文件带过来（会显示0kb）

![Snipaste_2024-07-17_15-26-56](https://github.com/user-attachments/assets/7273f69f-87c5-4f4a-998a-b771dfb2a038)
![Snipaste_2024-07-17_15-29-30](https://github.com/user-attachments/assets/ce15ae53-4f76-4c9b-bb52-fc79b8d2d208)

### Expected behavior

希望变成在复制第1次的结果上，把其位置和实际结果（有实际大小，如100kb）更新到最新位置上去，并去重

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.0.4",
  "tauriVersion": "1.7.1",
  "platform": "Windows_NT",
  "platformArch": "x86_64",
  "platformVersion": "10.0.22631"
}
```

**Comment by ayangweb** [comment]
收到反馈，文件类型的内容后面会进行样式和文件是否存在等问题进行一波大的优化！
