### ISSUE TITLE
[feat] 在面板上添加一个 **唤醒窗口** 按钮

### ISSUE THREAD

**Issue by RSS1102** [EcoPasteHub/EcoPaste#254]
### Describe the problem

用户第一次使用的时候可能不太了解软件使用，如果能将功能都以直接交互的情况下放在主页面感觉会比较好。

### Describe the solution you'd like

在主页面添加一个按钮，和**唤醒窗口**快捷键功能一致，两种方式让用户操作。

**Comment by ayangweb** [comment]
收到反馈，后续版本会支持！

**Comment by ayangweb** [comment]
windows 已经支持从托盘中打开剪贴板窗口，后续如果 mac 和 linux 需要可以在托盘里加个快捷打开的菜单！
