### ISSUE TITLE
[feat] 窗口位置，能否设置在光标闪烁的位置？

### ISSUE THREAD

**Issue by rmstsd** [EcoPasteHub/EcoPaste#264]
### Describe the problem

窗口位置，能否设置在光标闪烁的位置，而不是鼠标的位置，就像windows电脑上 按win+v快捷键那样（下图），我一直没有找到解决方案

![image](https://github.com/user-attachments/assets/6fabbcb1-8129-4df0-be02-f1c78b5524de)

### Describe the solution you'd like

窗口位置设置在光标闪烁的位置

**Comment by ayangweb** [comment]
收到反馈，我们会研究这个功能实现的可行性，可行的话在后续版本加入！

**Comment by rmstsd** [comment]
> 收到反馈，我们会研究这个功能实现的可行性，可行的话在后续版本加入！

搞定了吗大佬

**Comment by ayangweb** [comment]
还没，等我再研究研究

**Comment by rmstsd** [comment]
搞定了吗大佬

**Comment by ayangweb** [comment]
不打算支持

**Comment by rmstsd** [comment]
好叭
