### ISSUE TITLE
[feat] 支持自定义收藏标签，支持纯文本粘贴，支持对文本进行备注或标题

### ISSUE THREAD

**Issue by yanyu2015** [EcoPasteHub/EcoPaste#267]
### Describe the problem

- 希望能够支持标签自定义(最好支持多级分类)，最好是竖向排列，横向排列，则有点拥挤，感觉可以参考copyQ，它的排列如下
![image](https://github.com/user-attachments/assets/03d5341f-68cc-405b-9bfd-a1260649fc17)
- 希望支持粘贴纯文本，目前系统不支持纯文本粘贴，然后支持纯文本粘贴快捷键。比如ctrl+shift+V
- 增加粘贴项的标题或者备注功能，这样，其实剪切板不再是一个简单的 剪切板，而是带点便签性质的软件了，很多经考重复使用的功能，内容和文件都可以这样实现，但如果没有标题，只是显示一段话或者一个路经，就很难分辨。
- 

### Describe the solution you'd like

感谢开发者！

### Alternatives considered

无

### Additional context

无

**Comment by i-iooi-i** [comment]
![image](https://github.com/user-attachments/assets/967c2ca4-c4e6-49fc-a628-52a71c3defc9)
期待支持一下纯文本复制，现在chrome开了夜间模式，复制的一些页面的文字也自带黑色背景了。
 看着还是挺别扭的。 😂

**Comment by i-iooi-i** [comment]
![image](https://github.com/user-attachments/assets/f4bf0061-6cf3-46dc-bd27-ddcdd39a4dc8)
纯文本的话，看着就赏心悦目干净清爽多了。

**Comment by ayangweb** [comment]
自定义分组：Duplicate of #145

其它均完成！
