### ISSUE TITLE
[bug] 右键剪贴板内容会导致程序无响应

### ISSUE THREAD

**Issue by Seameee** [EcoPasteHub/EcoPaste#288]
### Describe the bug

使用快捷键打开剪贴板界面后，鼠标右键对应条目后程序出现无响应
![PixPin_2024-08-02_19-43-38](https://github.com/user-attachments/assets/27ecfc3b-48da-4af1-a740-53fab17f6cd2)

### Reproduction

我使用快捷键打开剪贴板界面后，鼠标右键对应条目后程序出现无响应

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.0.5",
  "tauriVersion": "1.7.1",
  "platform": "Windows_NT",
  "platformArch": "x86_64",
  "platformVersion": "10.0.19045"
}
```

**Comment by ayangweb** [comment]
谢谢反馈！方便留个联系方式吗？目前，我们在多台 Windows 测试机上都未能复现这个问题。

**Comment by ayangweb** [comment]
@Seameee 你好，0.0.6 已更新，再下载试一下，看看还会不会复现！

**Comment by ayangweb** [comment]
问题跟踪：https://github.com/c2r0b/tauri-plugin-context-menu/issues/29

**Comment by ayangweb** [comment]
fixed: https://github.com/c2r0b/tauri-plugin-context-menu/pull/31
