### ISSUE TITLE
[feat] 希望能隐藏菜单栏图标

### ISSUE THREAD

**Issue by GoodStudyDay** [EcoPasteHub/EcoPaste#289]
### Describe the problem

<img width="33" alt="image" src="https://github.com/user-attachments/assets/6f640f34-96f8-433b-ac71-ffbe98e0afd5">
该图标不可隐藏

### Describe the solution you'd like

希望可以增加一个配置项，去隐藏这个图标

**Comment by ayangweb** [comment]
收到反馈，我们将完善 MacOS 中从启动台打开 app 的问题。目前，app 启动一次后无法再次从启动台打开。如果能够有效解决这个问题，该功能将得到全面支持，敬请期待🌹

**Comment by ayangweb** [comment]
> 收到反馈，我们将完善 MacOS 中从启动台打开 app 的问题。目前，app 启动一次后无法再次从启动台打开。如果能够有效解决这个问题，该功能将得到全面支持，敬请期待🌹

很遗憾，https://github.com/libnyanpasu/clash-nyanpasu/issues/158#issuecomment-2315731954 这个问题看来在 tauri v1 解决起来很困难，如果隐藏了菜单栏的图标，那么想再次打开偏好设置窗口只能通过快捷键的方式，这显然有点鸡肋！

**Comment by ayangweb** [comment]
> 收到反馈，我们将完善 MacOS 中从启动台打开 app 的问题。目前，app 启动一次后无法再次从启动台打开。如果能够有效解决这个问题，该功能将得到全面支持，敬请期待🌹

我通过修改 `tao` 和 `tauri` 的源码，已经实现了此功能！隐藏图标的功能我下来会继续跟进研究一下！

**Comment by ayangweb** [comment]
> 收到反馈，我们将完善 MacOS 中从启动台打开 app 的问题。目前，app 启动一次后无法再次从启动台打开。如果能够有效解决这个问题，该功能将得到全面支持，敬请期待🌹

#473

**Comment by ayangweb** [comment]
#475 已支持！
