### ISSUE TITLE
[bug] 复制之后看不见内容

### ISSUE THREAD

**Issue by cethink** [EcoPasteHub/EcoPaste#311]
### Describe the bug

![image](https://github.com/user-attachments/assets/26f0a11a-4303-4fd2-8336-b174d9e2cddd)

![image](https://github.com/user-attachments/assets/604225a2-6382-4e86-a9f6-8301dc1e0f8a)

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.0.5",
  "tauriVersion": "1.7.1",
  "platform": "Windows_NT",
  "platformArch": "x86_64",
  "platformVersion": "10.0.22631"
}
```

**Comment by ayangweb** [comment]
收到反馈，方便录个视频复现一下吗？🌹

**Comment by cethink** [comment]
![动画](https://github.com/user-attachments/assets/1533ab10-f530-4deb-b641-83bcab86dbdf)
看图，还发现个问题，复制两次后就无效了，要重启应用才能继续

**Comment by ayangweb** [comment]
收到反馈，复制删掉以后你试试其它的内容能不能复制？

- https://github.com/ayangweb/EcoPaste/commit/b15f16133ee3c378c24a6797c163658daad7e663 
删掉无法再次复制相同内容的问题已修复，期待下个版本！

**Comment by cethink** [comment]
可以复制其它内容，但连续复制其它内容就又失效了，要换一个内容复制才有效

**Comment by ayangweb** [comment]
> 可以复制其它内容，但连续复制其它内容就又失效了，要换一个内容复制才有效

<img width="432" alt="image" src="https://github.com/user-attachments/assets/95e88d69-aee7-4fc5-b984-9d4fec88d331">

**Comment by ayangweb** [comment]
HTML 内容看不见属于是正常情况，HTML 内容会原模原样的输出，这个我们到时候准备做个空格预览功能来达到查看全部信息的功能🌹

**Comment by cethink** [comment]
看不见是因为文字是白色，如果选中是可以看见的，另外，通知区域图标单击能实现Alt+C的功能吗？而不是显示偏好设置

**Comment by cethink** [comment]
我一直在用CopyQ，啥都好，就是感觉丑了点，哎

**Comment by ayangweb** [comment]
> 看不见是因为文字是白色，如果选中是可以看见的，另外，通知区域图标单击能实现Alt+C的功能吗？而不是显示偏好设置

好，html 的内容显示我们下来再看看

单击托盘打开剪切板的功能看 #300

**Comment by ayangweb** [comment]
> 我一直在用CopyQ，啥都好，就是感觉丑了点，哎

有什么问题随时反馈，我们会努力做到更好🌹

**Comment by cethink** [comment]
🌹

**Comment by sevenyoung7** [comment]
我也碰到同样的问题，我用的深色模式，复制网页上的黑色文字，就会看不见，全黑了，跟黑色背景融在一起看不见，鼠标去选择的话，就可以看到（选择后会反色）。我觉得html的内容在预览时可以只显示纯文本即可（Win+V就是这样）。当然，如果大佬愿意折腾的话，可以在旁边另外加个小开关，控制是否显示颜色之类的。期待新版本解决。

**Comment by ayangweb** [comment]
> 我也碰到同样的问题，我用的深色模式，复制网页上的黑色文字，就会看不见，全黑了，跟黑色背景融在一起看不见，鼠标去选择的话，就可以看到（选择后会反色）。我觉得html的内容在预览时可以只显示纯文本即可（Win+V就是这样）。当然，如果大佬愿意折腾的话，可以在旁边另外加个小开关，控制是否显示颜色之类的。期待新版本解决。

<img width="730" alt="image" src="https://github.com/user-attachments/assets/ca943bb3-6504-493f-bbc1-855e11ae0d92">

新版本会支持这个功能！

**Comment by ayangweb** [comment]
这种很小概率出现的 html 内容的字体颜色和背景颜色一致的情况，不打算单独针对它们做处理，这会很复杂，也没有必要！
