### ISSUE TITLE
[feat] 纯文本粘贴支持自定义快捷键

### ISSUE THREAD

**Issue by whywayne2020** [EcoPasteHub/EcoPaste#320]
### Describe the problem

如题，很多时候粘贴到word，希望是纯文本。但是复制代码又要保留高亮语法等。

### Describe the solution you'd like

开放常用功能快捷键自定义。

**Comment by ayangweb** [comment]
收到反馈，后续版本会加入🌹

**Comment by sinomind** [comment]
强烈需要此功能，希望大佬可以尽快支持，谢谢。

**Comment by ayangweb** [comment]
> 强烈需要此功能，希望大佬可以尽快支持，谢谢。

https://github.com/EcoPasteHub/EcoPaste/pull/530 已经支持啦，期待下个版本！
