### ISSUE TITLE
[feat] 添加一个在剪贴板里再次编辑的功能

### ISSUE THREAD

**Issue by zhweji0505** [EcoPasteHub/EcoPaste#324]
### Describe the problem

可以添加一个在剪贴板里再次编辑的功能吗

### Describe the solution you'd like

可以添加一个在剪贴板里再次编辑的功能吗

**Comment by ayangweb** [comment]
收到反馈，这个看用户的需求量来决定🌹

**Comment by zhweji0505** [comment]
好的，感谢！

**Comment by Runarry** [comment]
本来我想提个查看长文本完整内容的需求，不过要是有编辑功能，貌似也可以直接解决我的需求
