### ISSUE TITLE
[feat] Global Shortcut support on Wayland

### ISSUE THREAD

**Issue by zpp0196** [EcoPasteHub/EcoPaste#337]

**Comment by suhanyujie** [comment]
以 ubuntu  为例，操作系统本身支持手动添加全局快捷键的呀，如下：
![image](https://github.com/user-attachments/assets/6b7d9e7a-0952-40b3-9e3e-029f4c471444)
![image](https://github.com/user-attachments/assets/8563b56e-8407-4653-8544-05ff6d2a192e)

**Comment by suhanyujie** [comment]
虽然说 wayland 下不支持添加全局热键，但是 [utools](https://u.tools/) 却实现了这个功能。我测试时，utools 安装后，能用 alt+Space 唤起它的窗口。不知道它是怎么实现的。

**Comment by suhanyujie** [comment]
ubuntu 24.04  x11 协议。存在的一些小问题：
- 双击不能自动粘贴，但可以将数据写入剪切板
- 图片不能预览：
![image](https://github.com/user-attachments/assets/db3fdc6c-4b46-4758-be5a-58802b8f4ae0)

**Comment by ayangweb** [comment]
EcoPaste 中剪贴板监听也不支持 wayland，所以不打算折腾快捷键功能
