### ISSUE TITLE
[feat] 没窗口的时候也有 webview 进程？有点占用资源

### ISSUE THREAD

**Issue by will5933** [EcoPasteHub/EcoPaste#382]
### Describe the problem

没窗口的时候也有 webview 进程？

![图片](https://github.com/user-attachments/assets/3d2b777e-731b-427f-956c-c2dcdea3ac9f)

### Describe the solution you'd like

```
tauri::Builder::default()
  .setup(|app| {
    let docs_window = tauri::WindowBuilder::new(
      app,
      "external", /* the unique window label */
      tauri::WindowUrl::External("https://tauri.app/".parse().unwrap())
    ).build()?;
    let local_window = tauri::WindowBuilder::new(
      app,
      "local",
      tauri::WindowUrl::App("index.html".into())
    ).build()?;
    Ok(())
  })
  .run(tauri::generate_context!())
  .expect("error while running app");
```

[用运行时窗口会不会更好一些？](https://tauri.app/v1/guides/features/multiwindow/#runtime-window)

**Comment by ayangweb** [comment]
收到反馈，这个需求我们会看一下可行性🌹

**Comment by ayangweb** [comment]
Duplicate of https://github.com/EcoPasteHub/EcoPaste/issues/497#issuecomment-2500118254
