### ISSUE TITLE
[bug] 在win7系统安装失败

### ISSUE THREAD

**Issue by fmssabby** [EcoPasteHub/EcoPaste#417]
### Describe the bug

在win7系统安装时显示：Windows Installer程序包有问题。作为安装一部分的 程序没有按预期完成。请与您的支持人员或程序包开发商联系。已基本查明Windows Installer程序应该没问题。
![微信截图_20240822144956](https://github.com/user-attachments/assets/7ab318f5-f575-4d7d-a7e6-f13fea41df4a)

### Application and system information

```text
Powerful open-source clipboard manager for MacOS and Windows platforms.
```

**Comment by ayangweb** [comment]
win7 需先下载电脑对应版本的 [webview2](https://developer.microsoft.com/en-us/microsoft-edge/webview2/?form=MA13LH#download)

**Comment by ayangweb** [comment]
由于长时间未收到回复，我将关闭此 issue。
