### ISSUE TITLE
[feat] 界面增加粘贴为纯文本功能按钮

### ISSUE THREAD

**Issue by whywayne2020** [EcoPasteHub/EcoPaste#450]
### Describe the problem

大量需要纯文本粘贴的场景。目前已经有右键菜单，但是界面上直接点击按钮会更方便。
![Uploading image.png…]()

### Describe the solution you'd like

如果右上方按钮支持自定义更好，比如说我不经常使用删除，则不需要显示删除按钮了。

**Comment by ayangweb** [comment]
收到反馈，后续版本会对内容的图标按钮进行调整
