### ISSUE TITLE
[bug] 严重问题，复制VS2022中代码后卡死！！！

### ISSUE THREAD

**Issue by cethink** [EcoPasteHub/EcoPaste#466]
### Describe the bug

![动画](https://github.com/user-attachments/assets/eec57e25-03e9-4659-8a7b-36b1d2297831)

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.0.6",
  "tauriVersion": "1.7.1",
  "platform": "Windows_NT",
  "platformArch": "x86_64",
  "platformVersion": "10.0.22631"
}
```

**Comment by ayangweb** [comment]
富文本问题已在 https://github.com/ayangweb/EcoPaste/issues/453 中修复！https://github.com/ayangweb/EcoPaste/actions/runs/10576046558 下载最新的测试版试试，然后再反馈看看！

Duplicate of #71 预览全部内容有大佬正在做全部内容的预览，敬请期待！

**Comment by cethink** [comment]
好了

**Comment by ayangweb** [comment]
欢迎加入微信群：https://github.com/ayangweb/EcoPaste?tab=readme-ov-file#community

**Comment by cethink** [comment]
好
