### ISSUE TITLE
[feat] 优化搜索时延迟方式

### ISSUE THREAD

**Issue by SimHapQ** [EcoPasteHub/EcoPaste#467]
### Describe the problem

实时搜索时有延迟，频繁全量查库。

### Describe the solution you'd like

 建议改为最近少量数据（自定义xx M）使用缓存，不设置延迟。 手动选择全量查询（对库表）时设置延迟防抖

**Comment by ayangweb** [comment]
收到反馈，后面我会考虑考虑，去掉搜索的防抖，实现实时响应！
