### ISSUE TITLE
[feat] 支持剪贴板内容的拖拽粘贴

### ISSUE THREAD

**Issue by trah01** [EcoPasteHub/EcoPaste#468]
### Describe the problem

现有截图只能通过右键下载，希望能够直接拖拽到文件夹里，可以参考copyQ。
同时历史记录只能设置天数过期，是否能够设置条数超限制过期，不仅仅是天数限制。

### Describe the solution you'd like

如上

**Comment by ayangweb** [comment]
收到反馈，这个功能有在计划当中，准备支持拖拽剪切板内容完成自动粘贴操作！🌹

**Comment by ayangweb** [comment]
1. under planning
2. Duplicate of #708
