### ISSUE TITLE
记住位置能否重启后不要重置位置？

### ISSUE THREAD

**Issue by Tincichow** [EcoPasteHub/EcoPaste#477]
### Describe the problem

因为习惯了放在一个固定的位置看，但是记住位置后，每次重启后位置都重置了，能否改成记住一个位置重启后都是在记住的位置上显示？

### Describe the solution you'd like

因为习惯了放在一个固定的位置看，但是记住位置后，每次重启后位置都重置了，能否改成记住一个位置重启后都是在记住的位置上显示？

**Comment by ayangweb** [comment]
你用的哪个版本？最新版是支持存储窗口位置的！

**Comment by Tincichow** [comment]
> 你用的哪个版本？ v0.0.6 是支持记住窗口位置的！

就是最新的0.6版本，每次重启电脑后都需要重新调整位置。不重启的话倒事可以固定位置。

**Comment by ayangweb** [comment]
我这边亲测有效，要不您卸载重装一下试试？

https://github.com/user-attachments/assets/4f7fe95d-96f2-48a7-8041-858a15800711

**Comment by Tincichow** [comment]
> 我这边亲测有效，要不您卸载重装一下试试？
> 
>  9.1.mov

卸载清除注册表，再重启重新安装，然后固定位置后再重启还是位置重置了。 - -！不晓得什么问题了。。。影响不大，只能慢慢习惯一下了哈哈。

**Comment by ayangweb** [comment]
会不会是其他软件或配置在重启电脑时清除了存储位置信息的隐藏文件，从而导致失效呢？

**Comment by Tincichow** [comment]
> 会不会是其他软件或配置在重启电脑时清除了存储位置信息的隐藏文件，从而导致失效呢？

我只装了火绒，看了一下也没有阻止和清除。之前用ditto也是可以固定位置重启后不变的。不晓得啥情况了- -！慢慢适应了。

**Comment by ayangweb** [comment]
好的，那我们先保持观察，暂时再等一段时间的反馈，看看是否有类似情况再次出现。

我先关闭这个 issue，如果有相同问题，我会重新开启。

**Comment by ayangweb** [comment]
忽然想到，你直接重启电脑并没有手动退出软件对吧？

**Comment by ayangweb** [comment]
#479 问题我已经修复了

https://github.com/EcoPasteHub/EcoPaste?tab=readme-ov-file#community

欢迎加入微信群，第一时间体验测试版本！

**Comment by Tincichow** [comment]
> [#479 ](https://github.com/EcoPasteHub/EcoPaste/pull/479) 问题我已经修复了
> 
> [https://github.com/EcoPasteHub/EcoPaste?tab=readme-ov-file#community ](https://github.com/EcoPasteHub/EcoPaste?tab=readme-ov-file#community)
> 
> 欢迎加入微信群，第一时间体验测试版本！

测试已经OK没问题了，谢谢大佬。

**Comment by ayangweb** [comment]
#479 实测还是有 bug，我们会继续跟进这个问题！

**Comment by ayangweb** [comment]
#493 已修复
