### ISSUE TITLE
[bug] ubuntu24下安装了打不开

### ISSUE THREAD

**Issue by cruvie** [EcoPasteHub/EcoPaste#478]
### Describe the bug

ubuntu24下安装了打不开

### Reproduction

安装
```shell
$ sudo apt install ./eco-paste_0.0.6_amd64.deb 
[sudo] cruvie 的密码： 
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
注意，选中 'eco-paste' 而非 './eco-paste_0.0.6_amd64.deb'
eco-paste 已经是最新版 (0.0.6)。
下列软件包是自动安装的并且现在不需要了：
  docker-ce-rootless-extras kwayland-data kwayland-integration
  libdbusmenu-qt5-2 libdouble-conversion3 libkf5config-bin libkf5config-data
  libkf5configcore5 libkf5coreaddons-data libkf5coreaddons5
  libkf5notifications-data libkf5notifications5 libkf5waylandclient5
  libkf5windowsystem-data libkf5windowsystem5 libmd4c0 libqt5core5t64
  libqt5dbus5t64 libqt5gui5t64 libqt5network5t64 libqt5qml5 libqt5qmlmodels5
  libqt5quick5 libqt5svg5 libqt5texttospeech5 libqt5waylandclient5
  libqt5waylandcompositor5 libqt5widgets5t64 libqt5x11extras5 libxcb-xinerama0
  libxcb-xinput0 pigz qt5-gtk-platformtheme qtspeech5-speechd-plugin
  qttranslations5-l10n qtwayland5 slirp4netns
使用'sudo apt autoremove'来卸载它(它们)。
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 3 个软件包未被升级。
```

### Expected behavior

安装后可以在应用中打开

### Application and system information

```text
eco-paste0.0.6

Ubuntu 24.04.1 LTS
```

**Comment by zpp0196** [comment]
提供一下在命令行启动的输出内容和日志文件 ~/.config/com.ayangweb.EcoPaste/logs

**Comment by cruvie** [comment]
cruvie@cruvie-Linux:~/下载$ eco-paste
eco-paste: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
cruvie@cruvie-Linux:~/下载$ ~/.config/com.ayangweb.EcoPaste/logs
bash: /home/cruvie/.config/com.ayangweb.EcoPaste/logs: 没有那个文件或目录

**Comment by zpp0196** [comment]
可以先暂时使用 AppImage 版本过渡等待后续修复

**Comment by cruvie** [comment]
临时解决办法
https://blog.csdn.net/qq_38798111/article/details/129848116
‵‵‵shell
echo "deb http://security.ubuntu.com/ubuntu focal-security main" | sudo tee /etc/apt/sources.list.d/focal-security.list
 
sudo apt-get update
sudo apt-get install libssl1.1
```
