### ISSUE TITLE
[bug] 快捷键设置无法保存

### ISSUE THREAD

**Issue by ElfenZ** [EcoPasteHub/EcoPaste#483]
### Describe the bug

更改【打开剪贴版窗口】快捷键，重启软件后恢复

### Reproduction

1. 默认快捷键设置为 Alt+C，修改默认快捷键为 Ctr+`
2. 重启软件，快捷键恢复为 Alt+C
3. 尝试使用管理员身份启动后修改，重启软件后依旧恢复为 Alt+C

### Expected behavior

保存用户修改快捷键

### Application and system information

```text
Windows11 23H2
EcoPaste 0.06
```

### Additional context

之前 Ctrl+` 用于 ditto，但这阵子 ditto 没有设置开机启动，应该不会自动占用回原有呼出快捷键

**Comment by ayangweb** [comment]
由于长时间未收到回复，我将关闭此 issue。
