### ISSUE TITLE
[bug] 已经添加辅助功能权限了，每次点开通用设置还是会要求权限 (Mac OS)

### ISSUE THREAD

**Issue by chww159** [EcoPasteHub/EcoPaste#490]
### Describe the bug

已经添加辅助功能权限了，每次点开通用设置还是会要求权限。
以及完全磁盘访问权限是能实现什么功能呢？为啥需要这个权限？
还有就是收到邮件说已支持隐藏菜单栏里的图标，但是没有在设置里找到此类选项哦。

### Application and system information

```text
Chip: Apple M3
Mac OS: 14.6.1
```

**Comment by ayangweb** [comment]
1、辅助功能删了重加下，属于系统级别的 bug 了
2、文件图片的展示需要，未来会展示视频等
3、还没发版，等正式版本或者 https://github.com/EcoPasteHub/EcoPaste/actions/runs/10673678185  最新测试版！

**Comment by ayangweb** [comment]
由于长时间未收到回复，我将关闭此 issue。
