### ISSUE TITLE
你好，是否可以添加图片预览放大功能

### ISSUE THREAD

**Issue by dgggh-56** [EcoPasteHub/EcoPaste#496]
### Describe the problem

如题
尊敬的开发者，您好EcoPaste能否添加Clipdiary像一样的功能，就是在观看预览图片的时候能够在软件界面之外放大图片，EcoPaste目前观看图片时只能在软件界面看，但是软件界面很小，要是复制了很多主体一样，但是里面的内容有一些区别的，这么小的软件端口看图片也很费力，甚至几乎可能看不到区别，就无法选择想要复制的哪个图片了。
![2024-09-07_191327](https://github.com/user-attachments/assets/0f30a8ec-af19-4df8-8cf6-4f13adfca0ee)

### Describe the solution you'd like

不加也可以的只是建议

### Alternatives considered

没有哈哈

### Additional context

额

**Comment by dgggh-56** [comment]
不好意思，之前添加图片没有成功，这次再添加一个
![Uploading 2024-09-07_191327.jpg…]()

**Comment by dgggh-56** [comment]
大佬再提几个小建议
1.能否像Clipdiary一样，在那个好像叫做状态栏的地方显示软件图标，这样在不置顶软件的情况下离开软件的话，再点击软件图标就能够再使用软件了，那个置顶功能确实不怎么好用，想要取消置顶的话要再点击一下软件，想让软件窗口消失的话，要点击一下软件，然后再按显示窗口快捷键再消失也是有一点麻烦的。![IMG_20240907_195254.jpg](https://github.com/user-attachments/assets/ebf858e1-de4f-4614-aed7-d723c375cd14)


2.第二点就是老生常谈的问题，能否让数据库不默认为c盘可以改到其他盘呢，c盘真的伤不起😂

**Comment by ayangweb** [comment]
图片放大目前是 空格键 可以用默认的图片查看器放大，后续会开发一个单独的窗口来支持所有的内容的单独查看！

1、任务栏图标的问题我会考虑做成配置项的方式！
2、Duplicate of #163 
3、快捷键的话可以用其它软件的快捷键转发的功能实现！

**Comment by ayangweb** [comment]
https://github.com/EcoPasteHub/EcoPaste/releases/tag/v0.1.0-beta.2

下载使用前请先手动备份好重要数据，然后再尝试更换路径！

**Comment by chergn** [comment]
挺不错，我现在mac用的PasteNow，收费！
一直很喜欢windows这种风格
![image](https://github.com/user-attachments/assets/2527c01e-0c97-4533-b24c-335e8bddb811)
现在有了开源免费的EcoPaste简直太棒了

**Comment by ayangweb** [comment]
> 挺不错，我现在mac用的PasteNow，收费！ 一直很喜欢windows这种风格 ![image](https://private-user-images.githubusercontent.com/43592730/367477211-2527c01e-0c97-4533-b24c-335e8bddb811.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNzg0NjMsIm5iZiI6MTcyNjI3ODE2MywicGF0aCI6Ii80MzU5MjczMC8zNjc0NzcyMTEtMjUyN2MwMWUtMGM5Ny00NTMzLWIyNGMtMzM1ZThiZGRiODExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDAxNDI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhMzNhZTZhZWE5MjRkYTNmNjU2MzRmZDIwY2M4MzE0MDZmY2UyZWJkNDhhNDVmMTIzYjA0Zjk3NmNiYWY3ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DFJq9Lk9Ex2rR-lDDN7lkr-Kpz_p_jJ6M6jxqLp8C7w) 现在有了开源免费的EcoPaste简直太棒了

感谢肯定🌹

**Comment by ayangweb** [comment]
任务栏图标显示的功能在 #576 实现了！

f1-f12 我参考了很多 app，可以考虑加入！

**Comment by dgggh-56** [comment]
> 任务栏图标显示的功能在 #576 实现了！
> 
> f1-f12 我参考了很多 app，可以考虑加入！

牛批，大佬你是最棒的

**Comment by ayangweb** [comment]
如果后续版本要常驻任务栏图标，必须要固定住，这是 tauri 的问题：https://github.com/tauri-apps/tauri/discussions/11107

**Comment by dgggh-56** [comment]
> 如果后续版本要常驻任务栏图标，必须要固定住，这是上游的问题：https://github.com/tauri-apps/tauri/discussions/11107

我发现一个问题，自己配置好之后，每次电脑重启之后都会变成默认的了，然后又需要配置，我都懒得配置了。😂

**Comment by dgggh-56** [comment]
> 如果后续版本要常驻任务栏图标，必须要固定住，这是上游的问题：https://github.com/tauri-apps/tauri/discussions/11107

我发现一个问题，每次配置好之后重启电脑配置都会变成默认的。

**Comment by ayangweb** [comment]
> > 如果后续版本要常驻任务栏图标，必须要固定住，这是上游的问题：[tauri-apps/tauri#11107](https://github.com/tauri-apps/tauri/discussions/11107)
> 
> 我发现一个问题，每次配置好之后重启电脑配置都会变成默认的。

Duplicate of #581
