### ISSUE TITLE
[bug] windows 上关闭 GUI 界面下的后台内存占用较高

### ISSUE THREAD

**Issue by dyphire** [EcoPasteHub/EcoPaste#497]
### Describe the bug

EcoPaste 在 windows 上关闭 GUI 界面后的后台内存占用较高，同样使用 webview2 进程的其他程序无此现象
![image](https://github.com/user-attachments/assets/f2cf12c4-7554-4224-a083-ec2ac37402ae)
观察了同样基于 Tauri 的 [pot-desktop](https://github.com/pot-app/pot-desktop) 和 [clash-nyanpasu](https://github.com/libnyanpasu/clash-nyanpasu) 内存占用行为：它们只在打开 GUI 界面和最小化时有着较高内存占用，当关闭 GUI 界面后 pot 和 clash-nyanpasu 会结束不需要的一些 webview2 进程从而维持了很低的后台内存占用

希望 EcoPaste 实现和 pot 及 clash-nyanpasu 类似的后台行为，关闭 GUI 界面后结束不再需要的一些 webview2 进程保持较低的后台内存占用

### Reproduction

打开 EcoPaste 后关闭 GUI 程序界面，观察后台的内存占用

### Expected behavior

当关闭 GUI 界面后，保持较低的后台内存占用

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.0.6",
  "tauriVersion": "1.7.1",
  "platform": "Windows_NT",
  "platformArch": "x86_64",
  "platformVersion": "10.0.22635"
}
```

**Comment by ayangweb** [comment]
收到反馈，我下来会学习参考一下前辈们的作品！
