### ISSUE TITLE
Mac os  version 14.5 剪切板粘贴无效

### ISSUE THREAD

**Issue by geekskai** [EcoPasteHub/EcoPaste#502]
### Describe the bug

无法粘贴，具体请看视频：输入正常，粘贴无效

https://github.com/user-attachments/assets/051d64c7-564a-4aa9-8ba3-88b6001e1715

### Application and system information

```text
Mac os version 14.5
EcoPaste v0.06
```

**Comment by ayangweb** [comment]
<img width="730" alt="image" src="https://github.com/user-attachments/assets/91de6d2a-7937-4d8d-b90e-6de08744a4f6">

请确保辅助功能访问权限已授权！

**Comment by geekskai** [comment]
确实辅助功能没有授权，但是，点击授权之后，弹窗显示输入密码，输入密码之后，似乎没有作用，还是授权失败

**Comment by ayangweb** [comment]
macos 的系统 bug，删了已有的重新加一下就可以了
