### ISSUE TITLE
[feat] 保存图片数据选项

### ISSUE THREAD

**Issue by angesong** [EcoPasteHub/EcoPaste#507]
### Describe the problem

现在复制图片时数据库保存的是当前图片的保存路径，一旦图片文件被删除，程序里保存的复制记录也将不可用。

### Describe the solution you'd like

增加一个选项，选择复制图片时保存路径或图片数据，选择报错数据时将复制的图片数据保存进数据库中，使用复制图片的记录时从数据库中读取图片

**Comment by ayangweb** [comment]
收到反馈，我们将对文件被删除后的显示进行整体优化。然而，关于保存图片数据的功能，可能无法实现，因为图片数据相对来说过于庞大。

**Comment by ayangweb** [comment]
Duplicate of #151
