### ISSUE TITLE
[feat] 建议界面更加紧凑一点，大部分情况最多看下开头2行即可判断是否是自己想要的

### ISSUE THREAD

**Issue by lhtuling** [EcoPasteHub/EcoPaste#508]
### Describe the problem

呼出的窗口太过于大了

### Describe the solution you'd like

可以出个紧凑模式设置，每条信息只显示N行这样的更好

**Comment by ayangweb** [comment]
收到反馈，后续版本会进行优化！

**Comment by chergn** [comment]
就像Windows这种是吧？
![image](https://github.com/user-attachments/assets/7a7c91db-782f-4832-9590-3782d07a385a)

**Comment by witt-bit** [comment]
看上面Windows的截图，可以把剪贴板项置顶的这个抄过来，这个比较有用


目前含空间主要是高度吧
