### ISSUE TITLE
能不能像qq那样靠边自动收缩！

### ISSUE THREAD

**Issue by MyACGN** [EcoPasteHub/EcoPaste#509]
能不能像qq那样靠边自动收缩

**Comment by chergn** [comment]
真希望这个仓库能开启github discussions讨论模块
![image](https://github.com/user-attachments/assets/8a16db2d-b1a4-4d6d-be6e-d5bfe92e15dd)

**Comment by ayangweb** [comment]
> 真希望这个仓库能开启github discussions讨论模块 ![image](https://private-user-images.githubusercontent.com/43592730/367477516-8a16db2d-b1a4-4d6d-be6e-d5bfe92e15dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNzcwNzEsIm5iZiI6MTcyNjI3Njc3MSwicGF0aCI6Ii80MzU5MjczMC8zNjc0Nzc1MTYtOGExNmRiMmQtYjFhNC00ZDZkLWJlNmUtZDViZmU5MmUxNWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDAxMTkzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3ZjdmZjBhNDE4MWIxZGM1NDU5NjQ3MGRkMDRiNGM4NzkyOWRlNWNlNTQyODEzN2JhNDY1YTE5YWQyYjE4ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._KxRjufDy5kQ8DyaPZJiWgFmEjF8nNWhM3x42LeSMss)

不太好管理，所以只开了 issue，不过可以加入[微信群](https://github.com/EcoPasteHub/EcoPaste?tab=readme-ov-file#community)
