### ISSUE TITLE
[bug] 使用小狼毫输入法输入中文进行搜索时界面会卡住

### ISSUE THREAD

**Issue by Yofk** [EcoPasteHub/EcoPaste#524]
### Describe the bug

小狼毫输入法最新版
输入英文能正常搜索。输入中文时无法出现选字框，ecopaste主界面就会卡住，无法响应操作。
![PixPin_2024-09-15_21-40-48](https://github.com/user-attachments/assets/80f28b37-befb-4655-ac8e-f0f2a6217bee)
卡住会一直固定在屏幕上，只能通过右键任务栏图标重新激活ecopaste。使用微软拼音能正常搜索中文

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.1.0-beta.3",
  "tauriVersion": "1.7.2",
  "platform": "Windows_NT",
  "platformArch": "x86_64",
  "platformVersion": "10.0.19045"
}
```

**Comment by dyphire** [comment]
这是小狼毫自身的 bug，见 https://github.com/rime/weasel/issues/1341#issuecomment-2265038457

尝试下载小狼毫的每日构建版安装试试有没有修复，还能复现的话向小狼毫报告

**Comment by ayangweb** [comment]
> 这是小狼毫自身的 bug，见 [rime/weasel#1341 (comment)](https://github.com/rime/weasel/issues/1341#issuecomment-2265038457)
> 
> 尝试下载小狼毫的每日构建版安装试试有没有修复，还能复现的话向小狼毫报告

@Yofk 你也下载修改版试试呢

**Comment by Yofk** [comment]
> 这是小狼毫自身的 bug，见 [rime/weasel#1341 (comment)](https://github.com/rime/weasel/issues/1341#issuecomment-2265038457)
> 
> 尝试下载小狼毫的每日构建版安装试试有没有修复，还能复现的话向小狼毫报告

安装了小狼毫的nightly版还是一样，请问你使用小狼毫时有解决这个问题吗？

**Comment by dyphire** [comment]
> > 这是小狼毫自身的 bug，见 [rime/weasel#1341 (comment)](https://github.com/rime/weasel/issues/1341#issuecomment-2265038457)
> > 尝试下载小狼毫的每日构建版安装试试有没有修复，还能复现的话向小狼毫报告
> 
> 安装了小狼毫的nightly版还是一样，请问你使用小狼毫时有解决这个问题吗？

我用的是上面评论里提到的修改版，可以正常使用
小狼毫的 nightly 版说是修复了该 issue，但我没有试过，如果你那边依然复现的话最好在小狼毫那边打开新的 issue 进行报告，等待开发者修复
