### ISSUE TITLE
[bug] 在输入框输入时唤出EcoPaste会退出输入状态

### ISSUE THREAD

**Issue by iaw-dlay** [EcoPasteHub/EcoPaste#526]
### Describe the bug

在输入框进行输入时使用EcoPaste会导致退出输入状态，再点击输入框又会退出EcoPaste
演示是用的鼠标手势软件按快捷键，直接使用快捷键唤出EcoPaste也是同样的情况（我设置的快捷键是Alt+[，也更换过快捷键来确认是软件自身的问题而不是快捷键对输入框的影响）

输入时唤出EcoPaste：
https://github.com/user-attachments/assets/8dacc63a-e169-4505-8f2a-8a39111b0f52

win+v唤出windows自带的剪贴板时并不会导致这种情况，点击剪贴板内容就能粘贴到输入框里
简单测试了其他输入框，不仅Google搜索栏，Google地址栏、github搜索栏、windows文件资源管理器、和QQ的输入框，均是一样的情况

### Application and system information

```text
windows版本：Windows 专业版 22H2
EcoPaste版本：v0.0.6
```

**Comment by iaw-dlay** [comment]
系统信息漏了一点：
Windows 10 专业版 19045.4894

这个是windows自带的剪贴板的情况
https://github.com/user-attachments/assets/938f5571-0e9e-4665-a635-27b6e8a57937

**Comment by iaw-dlay** [comment]
系统信息漏了一点：
Windows 10 专业版 22H2 19045.4894

这个是windows自带的剪贴板的情况
https://github.com/user-attachments/assets/938f5571-0e9e-4665-a635-27b6e8a57937

**Comment by ayangweb** [comment]
Duplicate of #28 

问题重复，此 issue 将被关闭，等待后续版本支持！

不过你这个鼠标手势唤出 EcoPaste，有点酷😎
