### ISSUE TITLE
[feat] When you press the Enter key, the content is pasted directly.

### ISSUE THREAD

**Issue by Republic1024** [EcoPasteHub/EcoPaste#527]
### Describe the problem

![image](https://github.com/user-attachments/assets/e52cfa23-22b4-4c05-83c9-5e5807a460cc)

 The current problem is that after selecting an item from the clipboard, pressing the Enter key does not paste the content directly. Instead, you have to manually click on the item or press Ctrl + V to paste it. I would like to streamline this process so that pressing Enter automatically pastes the selected clipboard content.

当前的问题是，在剪切板中选择了一项内容后，按下 Enter 键无法直接粘贴。相反，需要手动点击该内容或者按 Ctrl + V 才能完成粘贴。希望能简化这个过程，使按下 Enter 键时可以自动粘贴所选的剪切板内容。

### Describe the solution you'd like

Modify the clipboard behavior so that when the Enter key is pressed after selecting an item, the content is pasted directly without the need for additional actions. This allows for a more efficient and streamlined process, enabling quick pasting by simply pressing Enter.

修改剪切板的行为，使在选择一项内容后按下 Enter 键时，直接粘贴该内容，无需其他操作。这样可以使粘贴过程更加高效，按下 Enter 键即可快速粘贴。

**Comment by ayangweb** [comment]
你是什么系统的电脑？用的哪个版本的 EcoPaste

**Comment by Republic1024** [comment]
没事了，重启之后又好了。 我的版本是EcoPaste_0.0.6_x64_zh-CN.msi，win10系统
