### ISSUE TITLE
[bug] 无法开机自启，设置被重置

### ISSUE THREAD

**Issue by DD6DD** [EcoPasteHub/EcoPaste#532]
### Describe the bug

[bug] 在设置界面设置了开机启动，但是电脑开机后发现EcoPaste并未启动。手动打开Ecopaste后，其内部设置项，如开机启动、保存天数等设置项全都被重置。

### Application and system information

```text
Windows 11 home
```

**Comment by ayangweb** [comment]
卸载重装试试，目前还没定位到这个问题产生的原因，大多数人卸载重装就好了！

**Comment by DD6DD** [comment]
> 卸载重装试试，目前还没定位到这个问题产生的原因，大多数人卸载重装就好了！

我装了beta版本，没这些问题了😂

**Comment by ayangweb** [comment]
> > 卸载重装试试，目前还没定位到这个问题产生的原因，大多数人卸载重装就好了！
> 
> 我装了beta版本，没这些问题了😂

好哒，这周应该就会发稳定版本啦🥰
