### ISSUE TITLE
[bug] 通过brew方式安装后，点击快捷方式打开提示已损坏

### ISSUE THREAD

**Issue by Ninohana** [EcoPasteHub/EcoPaste#533]
### Describe the bug

AT

### Application and system information

```text
macOS M3
```

**Comment by ayangweb** [comment]
https://github.com/EcoPasteHub/EcoPaste/blob/master/README.zh-CN.md#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
