### ISSUE TITLE
[bug] eco-paste : Depends: libwebkit2gtk-4.0-37 but it is not installable

### ISSUE THREAD

**Issue by bethmole** [EcoPasteHub/EcoPaste#534]
### Describe the bug

ubuntu24.04 install error:
udo dpkg -i eco-paste_0.1.0-beta.5_amd64.deb
dpkg: warning: parsing file '/var/lib/dpkg/tmp.ci/control' near line 10 package 'eco-paste':
 missing 'Maintainer' field
Selecting previously unselected package eco-paste.
(Reading database ... 306627 files and directories currently installed.)
Preparing to unpack eco-paste_0.1.0-beta.5_amd64.deb ...
Unpacking eco-paste (0.1.0-beta.5) ...
dpkg: dependency problems prevent configuration of eco-paste:
 eco-paste depends on libwebkit2gtk-4.0-37; however:
  Package libwebkit2gtk-4.0-37 is not installed.

dpkg: error processing package eco-paste (--install):
 dependency problems - leaving unconfigured
Processing triggers for bamfdaemon (0.5.6+22.04.20220217-0ubuntu5) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for gnome-menus (3.36.0-1.1ubuntu3) ...
Processing triggers for desktop-file-utils (0.27-2build1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 eco-paste

### Application and system information

```text
ubuntu 24.04
```

**Comment by AuroraTea** [comment]
This is an upstream issue.
I also have encountered it. Currently, I am relying on adding the sources for Ubuntu 22.04.

You might find it helpful to refer to this issue for more information.
https://github.com/tauri-apps/tauri/issues/9662

**Comment by ayangweb** [comment]
Hey 👋, according to https://github.com/tauri-apps/tauri/issues/9662#issuecomment-2389556534 and https://github.com/tauri-apps/tauri/issues/9662#issuecomment-2397022147, tauri v2 seems to have solved the problem, and we've upgraded EcoPaste to tauri v2! Download the installer from the link below and give it a try!

https://github.com/EcoPasteHub/EcoPaste/actions/runs/11304321774

**Comment by ayangweb** [comment]
长时间未回复，我先关了，tauri v2 看样子是已经修复了！有问题我再打开
