### ISSUE TITLE
[feat] 托盘图标不清晰和提供数据保存到安装目录的便携版程序

### ISSUE THREAD

**Issue by 1208041822** [EcoPasteHub/EcoPaste#546]
### Describe the problem

托盘图标不清晰和提供数据保存到安装目录的便携版程序

### Describe the solution you'd like

托盘图标不清晰和提供数据保存到安装目录的便携版程序

**Comment by WyInnovate** [comment]
图标阳佬在处理了
便携版程序计划中好像，详细情况加群

**Comment by ayangweb** [comment]
托盘图标不清晰的问题很遗憾是上游的问题！

https://github.com/tauri-apps/tauri/issues/11067#issuecomment-2362510445

**Comment by ayangweb** [comment]
便携版我不打算折腾，最新版已经支持了自定义数据存储路径，可以自己捣鼓一下！

**Comment by 1208041822** [comment]
> 便携版我不打算折腾，最新版已经支持了自定义数据存储路径，可以自己捣鼓一下！

好的！
