### ISSUE TITLE
[bug] 选中内容右键以后再打开别的软件窗口就卡死了

### ISSUE THREAD

**Issue by WyInnovate** [EcoPasteHub/EcoPaste#547]
### Describe the bug

1. 打开剪贴板列表
2. 选中其中一条数据
3. 右键打开操作菜单
4. 在右键菜单打开的情况，打开微信窗口
5. 出现卡死情况，后续会未响应
6. 详情看录屏

https://github.com/user-attachments/assets/57770f69-db01-4203-bc21-f675654daf73

### Application and system information

```text
v0.1.0-rc.1
```

**Comment by WyInnovate** [comment]
补充情况：PowerShell tauri dev情况下，不会出现问题

**Comment by ayangweb** [comment]
#288 跟这个应该是一样的问题，也就是说本地跑起来的项目不会崩溃，只有生产环境的崩溃，我去复现一下试试！

**Comment by db-one** [comment]
我的也有这个问题，WIN11 23H2，目前已经删除了数据文件，重新观察一下

**Comment by ayangweb** [comment]
问题跟踪：https://github.com/c2r0b/tauri-plugin-context-menu/issues/29

**Comment by ayangweb** [comment]
fixed: https://github.com/c2r0b/tauri-plugin-context-menu/pull/31

**Comment by ayangweb** [comment]
Duplicate of #288
