### ISSUE TITLE
[bug] macOS辅助功能授权无效

### ISSUE THREAD

**Issue by willron** [EcoPasteHub/EcoPaste#548]
### Describe the bug

![image](https://github.com/user-attachments/assets/d226857e-3aab-43df-bdc1-107b73a1e89f)
![QQ_1726718932795](https://github.com/user-attachments/assets/16c68d6d-ef57-4c40-8d8e-77ade7003ee9)
已经完成辅助功能的授权，但还是提示无权限
试过关闭授权，重启软件，再次授权，再次重启软件均无效

### Application and system information

```text
Mac mini M1
macOS Sequoia 15.0
```

**Comment by ayangweb** [comment]
把已有的一列删除，手动加一下！

**Comment by willron** [comment]
问题已解决。一开始手动删除添加没作用。后面用这种步骤解决的：
运行应用 -> 提示授权 -> 跳转到设置 ->  处于已授权状态  ->  点选应用点-删除  ->  退出设置和应用  ->  重新打开应用  ->   提示授权  ->  跳转设置  ->  列表中出现应用  ->  处于未授权状态  ->  授权即可

**Comment by ayangweb** [comment]
> 问题已解决。一开始手动删除添加没作用。后面用这种步骤解决的： 运行应用 -> 提示授权 -> 跳转到设置 -> 处于已授权状态 -> 点选应用点-删除 -> 退出设置和应用 -> 重新打开应用 -> 提示授权 -> 跳转设置 -> 列表中出现应用 -> 处于未授权状态 -> 授权即可

OK，这个确实有点麻烦的，因为应用只要是没有走苹果官方的签名（99美元/年），就没办法做到更新保持原有的权限！
