### ISSUE TITLE
[bug] 窗口背景样式丢失？

### ISSUE THREAD

**Issue by Ninohana** [EcoPasteHub/EcoPaste#549]
### Describe the bug

![QQ_1726731188606](https://github.com/user-attachments/assets/7de317eb-c79b-46d7-beca-ce04afd57df7)

### Application and system information

```text
macOS M3
```

**Comment by Ninohana** [comment]
![QQ_1726731349102](https://github.com/user-attachments/assets/4eea3bd1-0f71-4f8a-810b-6c224ed2d3be)
或许是特性？

**Comment by ayangweb** [comment]
<img width="730" alt="image" src="https://github.com/user-attachments/assets/ebe44a39-dad9-4147-bced-f85e31d9c800">

看下辅助功能访问权限给了没！没给的话给一下，给了的话重启一下试试！
