### ISSUE TITLE
[bug] 时间错误

### ISSUE THREAD

**Issue by policx** [EcoPasteHub/EcoPaste#559]
### Describe the bug

![image](https://github.com/user-attachments/assets/cefad04e-526c-45c7-8fe0-a1a46ab967f6)

### Application and system information

```text
时间错误
```

**Comment by ayangweb** [comment]
抱歉，我的疏忽，没有测试到 v0.0.6 升级到 v1.0.0 之后的数据问题，旧数据都出问题了☹️

**Comment by ayangweb** [comment]
非常抱歉，我已经删除了最新的安装包。我会重新测试和优化，确保将风险降到最低后再发布新版本。☹️

**Comment by ayangweb** [comment]
我已经重新发版，深感抱歉🥹
