### ISSUE TITLE
[feat] 紧凑的视图和自定义图片缩略图的尺寸

### ISSUE THREAD

**Issue by wusumu** [EcoPasteHub/EcoPaste#562]
### Describe the problem

紧凑的视图和自定义图片缩略图的尺寸

### Describe the solution you'd like

紧凑的视图和自定义图片缩略图的尺寸

**Comment by ayangweb** [comment]
#508 #271 跟这些差不多吧！

**Comment by 1208041822** [comment]
> #508 #271 跟这些差不多吧！

差不多

**Comment by coulsonpl** [comment]
> #508 #271 跟这些差不多吧！

建议参考 [Clipy](https://github.com/Clipy/Clipy) 出个精简模式，一行一个文本，用序号标记分组
![image](https://github.com/user-attachments/assets/f1ee5bbe-23ea-4949-b327-c8fd3bcb0ded)

**Comment by ayangweb** [comment]
Duplicate of #271 等支持
