### ISSUE TITLE
[bug] 从0.05和0.06升级到最新版，没法读取数据库和设置偏好。必须把旧版完全删除，或者导出再导入

### ISSUE THREAD

**Issue by XianYuDaXian** [EcoPasteHub/EcoPaste#563]
### Describe the bug

升级后发现软件历史记录空白，而且复制进去的内容在关闭软件后再打开也会丢失，跟无法读取数据库一样。手动把数据目录删除或者导出旧版再新版导入后解决，然后导入的记录全部时间都错乱，变成25年以前。

### Reproduction

升级后发现软件历史记录空白，而且复制进去的内容在关闭软件后再打开也会丢失，跟无法读取数据库一样。手动把数据目录删除或者导出旧版再新版导入后解决，然后导入的记录全部时间都错乱，变成25年以前。

### Application and system information

```text
win11 23H2
```

**Comment by ayangweb** [comment]
https://github.com/EcoPasteHub/EcoPaste/issues/559

很抱歉，我的疏忽！

**Comment by ayangweb** [comment]
从 0.0.6 升级到昨晚发的版才是好的，前天的版本有破坏性 bug，数据库的数据全乱了☹️
