### ISSUE TITLE
[bug] 下载新版本sha256 不匹配

### ISSUE THREAD

**Issue by Kronight** [EcoPasteHub/EcoPaste#564]
### Describe the bug

安装命令及步骤：
➜  ~ brew tap EcoPasteHub/EcoPaste             
➜  ~ brew install ecopastehub/ecopaste/ecopaste
==> Downloading https://mirror.ghproxy.com/https://github.com/ayangweb/EcoPaste/releases/latest/download/EcoPaste_aarch64.app.tar.gz
Already downloaded: /Users/kronight/Library/Caches/Homebrew/downloads/2b6c9a97118578185aba5f58f741d3246b64a9c234ca7477e87822805c5e467b--EcoPaste_aarch64.app.tar.gz
Error: SHA256 mismatch
Expected: c4c8d3457a222d9f0ae9836bde1be7c023834bf2d7358f3c1f49bea7c3a56601
  Actual: fde655338768c73f4e136ace5abbd4bf9fa133af1d2fe8b82473cdb79329b2d2
    File: /Users/kronight/Library/Caches/Homebrew/downloads/2b6c9a97118578185aba5f58f741d3246b64a9c234ca7477e87822805c5e467b--EcoPaste_aarch64.app.tar.gz
To retry an incomplete download, remove the file above.

### Application and system information

```text
Macos 15.0 (24A335)
Homebrew 4.3.23
zsh
iterm
```

**Comment by ayangweb** [comment]
感谢反馈，已更新，再试试！
