### ISSUE TITLE
[bug] 设置界面，通用设置拉到底，切换到快捷键设置界面，右则出现排版异常

### ISSUE THREAD

**Issue by willron** [EcoPasteHub/EcoPaste#566]
### Describe the bug

https://github.com/user-attachments/assets/ffc4d981-d741-4976-8384-9e6f9e573578

### Application and system information

```text
设置界面，通用设置拉到底，切换到快捷键设置界面，右则出现排版异常
发现问题后，复现了一次，录屏时复现了一次，后面再无法复现了
```

**Comment by ayangweb** [comment]
收到反馈，我试试复现修复一下！

**Comment by willron** [comment]
出现异常后，点击回通用设置，右则**依然处于底部状态**，滑动回顶部状态，再切换回快捷键页面，这时能恢复正常。

无法复现问题时，应用表现不一样。通用设置拉到底，切换快捷键无异常，切换回通用设置，**这个时候是顶部状态**

**Comment by ayangweb** [comment]
大概知道怎么解决，我弄一下！

**Comment by ayangweb** [comment]
我准备做成记住上个页面位置，你觉得如何？
