### ISSUE TITLE
[bug] Macos brew安装依旧有问题

### ISSUE THREAD

**Issue by Kronight** [EcoPasteHub/EcoPaste#567]
### Describe the bug

~ brew tap EcoPasteHub/EcoPaste
➜  ~ brew install ecopastehub/ecopaste/ecopaste
HOMEBREW_BREW_GIT_REMOTE set: using https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git as the Homebrew/brew Git remote.
remote: Enumerating objects: 80, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 80 (delta 22), reused 20 (delta 20), pack-reused 51
Unpacking objects: 100% (80/80), 54.52 KiB | 2.18 MiB/s, done.
From https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew
   404666b60e..26c6d5a0e8  back-to-srb -> origin/back-to-srb
 + 20bbdafee6...16caafe6c1 no-undefs   -> origin/no-undefs  (forced update)
==> Auto-updating Homebrew...
Adjust how often this is run with HOMEBREW_AUTO_UPDATE_SECS or disable with
HOMEBREW_NO_AUTO_UPDATE. Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
error: could not apply 55de5f4... v0.1.0
Could not apply 55de5f4... v0.1.0
error: could not apply 55de5f4... v0.1.0
Could not apply 55de5f4... v0.1.0
Error: Failed to download https://formulae.brew.sh/api/formula.jws.json!
Failed to download https://formulae.brew.sh/api/cask.jws.json!
Failed to download https://formulae.brew.sh/api/formula_tap_migrations.jws.json!
Failed to download https://formulae.brew.sh/api/cask_tap_migrations.jws.json!
==> Auto-updated Homebrew!
Updated 3 taps (ayangweb/ecopaste, ecopastehub/ecopaste and homebrew/command-not-found).

Warning: Cask 'ecopaste' is unreadable: /opt/homebrew/Library/Taps/ecopastehub/homebrew-ecopaste/Casks/ecopaste.rb:5: syntax error, unexpected <<
<<<<<<< HEAD
^~
/opt/homebrew/Library/Taps/ecopastehub/homebrew-ecopaste/Casks/ecopaste.rb:11: syntax error, unexpected ===
=======
^~~
/opt/homebrew/Library/Taps/ecopastehub/homebrew-ecopaste/Casks/ecopaste.rb:17: syntax error, unexpected >>
>>>>>>> 55de5f4 (v0.1.0)
^~
/opt/homebrew/Library/Taps/ecopastehub/homebrew-ecopaste/Casks/ecopaste.rb:17: unexpected fraction part after numeric literal
>>>>>>> 55de5f4 (v0.1.0)
                   ^~~~
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################### 100.0%
==> Searching for similarly named formulae and casks...
==> Downloading https://formulae.brew.sh/api/cask.jws.json
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to formulae.brew.sh:443

Warning: cask.jws.json: update failed, falling back to cached version.
Error: Cask 'ecopaste' is unreadable: /opt/homebrew/Library/Taps/ayangweb/homebrew-ecopaste/Casks/ecopaste.rb:5: syntax error, unexpected <<
<<<<<<< HEAD
^~
/opt/homebrew/Library/Taps/ayangweb/homebrew-ecopaste/Casks/ecopaste.rb:11: syntax error, unexpected ===
=======
^~~
/opt/homebrew/Library/Taps/ayangweb/homebrew-ecopaste/Casks/ecopaste.rb:17: syntax error, unexpected >>
>>>>>>> 55de5f4 (v0.1.0)
^~
/opt/homebrew/Library/Taps/ayangweb/homebrew-ecopaste/Casks/ecopaste.rb:17: unexpected fraction part after numeric literal
>>>>>>> 55de5f4 (v0.1.0)
                   ^~~~

### Application and system information

```text
macos 15
```

**Comment by ayangweb** [comment]
感谢反馈，仓库地址忘改了！现在可以了！

记得先卸载 ayangweb 仓库的！

```bash
brew uninstall --cask ecopaste

brew untap ayangweb/EcoPaste
```

```bash
brew tap EcoPasteHub/EcoPaste

brew install ecopaste
```

<img width="1050" alt="image" src="https://github.com/user-attachments/assets/e8b4d83b-083a-4c04-a0ac-21a7e3fb3695">
