### ISSUE TITLE
[bug] 下载的EcoPaste_0.1.0_x64-setup.exe windows11 双击没有反应

### ISSUE THREAD

**Issue by xiaomo1135** [EcoPasteHub/EcoPaste#575]
### Describe the bug

下载的EcoPaste_0.1.0_x64-setup.exe windows11 双击没有反应

### Application and system information

```text
windows11 手工升级
```

**Comment by ayangweb** [comment]
收到反馈，这个我们我们下来排查下！

**Comment by HujwCreator** [comment]
> 收到反馈，这个我们我们下来排查下！

我mac上也是，双击后没有粘贴到输入位置，和这个是同样的问题吗？
系统版本：macOS Sequoia 15.0

**Comment by ayangweb** [comment]
> > 收到反馈，这个我们我们下来排查下！
> 
> 我mac上也是，双击后没有粘贴到输入位置，和这个是同样的问题吗？ 系统版本：macOS Sequoia 15.0

mac 如果没有自动粘贴的话，看看是不是没有给辅助功能访问权限！
<img width="730" alt="image" src="https://github.com/user-attachments/assets/a7fab17a-c862-4d88-a521-ace498c5c713">

**Comment by HujwCreator** [comment]
> > > 收到反馈，这个我们我们下来排查下！
> > 
> > 
> > 我mac上也是，双击后没有粘贴到输入位置，和这个是同样的问题吗？ 系统版本：macOS Sequoia 15.0
> 
> mac 如果没有自动粘贴的话，看看是不是没有给辅助功能访问权限！ <img alt="image" width="730" src="https://private-user-images.githubusercontent.com/75017711/370960848-a7fab17a-c862-4d88-a521-ace498c5c713.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMTkyMTgsIm5iZiI6MTcyNzMxODkxOCwicGF0aCI6Ii83NTAxNzcxMS8zNzA5NjA4NDgtYTdmYWIxN2EtYzg2Mi00ZDg4LWE1MjEtYWNlNDk4YzVjNzEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDAyNDgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMjc1MDk1ZWI5Yzc2NTkwNDc4ZTNmNzYyODJkZTZlMmQ0NGFjYTYwYzhlMWQ2MjRiNDlhYTQyYzYwOGJkNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Z785UYSSPVpNe_sUrjd8DQP_hekKoBUsmxvwU0t8XM8">
> 
> Duplicate of #502

权限有加的，重新安装重新给权限也还是不行，不知道是macOS15这个版本的问题还是我电脑的问题。
<img width="736" alt="image" src="https://github.com/user-attachments/assets/8508e2a1-5b13-4457-aac9-a2075cd84f4c">

**Comment by ayangweb** [comment]
好，我新开了个 issue，我下来看看！

**Comment by ayangweb** [comment]
@HujwCreator 加[微信群](https://github.com/EcoPasteHub/EcoPaste?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) 我找了朋友的 macos15 他电脑可以了，你也帮忙测试下！
