### ISSUE TITLE
[bug] 快捷键无法正常唤起粘贴板

### ISSUE THREAD

**Issue by Veng0923** [EcoPasteHub/EcoPaste#578]
### Describe the bug

1. 正常下载安装eco-paste-0.1.0 ( 我的系统是linux mint 22) 下载appimage直接窗口无法正常显示, 用deb窗口可以正常显示;
2. 正常复制, 快捷键唤起粘贴板历史
3. 唤起粘贴板窗口有三个问题: 1. 粘贴板窗口不是置顶的; 2.窗口有时候不会自动关闭, 想手动关闭没有关闭按钮; 3. 多次使用快捷键唤起,大概率无法正常唤起;
我的系统信息:
![image](https://github.com/user-attachments/assets/0c61c1da-6773-44fa-b177-5b16619cbc66)

### Application and system information

```text
version: 0.1.0
system: linux mint 22 Cinnamon 6.2.7
```

**Comment by AuroraTea** [comment]
第一点的话我的Ubuntu24.04是可以运行AppImage版的
第三点的话我看了下现在
一方面是按快捷键后toggleWindowVisible不一定被触发
一方面刚唤出来的窗口appWindow.isFocused()就是false
这两点好像都得追溯到tauri去了

我都再看看😂头疼
说起来你是x11还是Wayland

**Comment by witt-bit** [comment]
> 第一点的话我的Ubuntu24.04是可以运行AppImage版的 第三点的话我看了下现在 一方面是按快捷键后toggleWindowVisible不一定被触发 一方面刚唤出来的窗口appWindow.isFocused()就是false 之前appWindow.setFocus()可以用的现在竟然没用 这两点好像都得追溯到tauri去了
> 
> 我都再看看😂头疼 说起来你是x11还是Wayland

我也有这个问题，部分软件界面不行，X11
