### ISSUE TITLE
[bug] 通过scoop升级，新旧版本数据不能同步

### ISSUE THREAD

**Issue by XylonMystic** [EcoPasteHub/EcoPaste#579]
### Describe the bug

![PixPin_2024-09-25_09-43-44](https://github.com/user-attachments/assets/98c63c7f-c478-47c8-9af3-222c7a4863a8)

收藏全无

### Application and system information

```text
1
```

**Comment by XylonMystic** [comment]
> 啥时候更新的版本！

昨天    Version     : 0.1.0

**Comment by ayangweb** [comment]
0.0.6 手动覆盖安装到 0.1.0 吗

**Comment by ayangweb** [comment]
版本是从 github 下载的最新的吗？

**Comment by XylonMystic** [comment]
> 版本是从 github 下载的最新的吗？

![PixPin_2024-09-25_09-54-38](https://github.com/user-attachments/assets/8748c694-085c-46c4-a4e9-3d8c4cfbc760)
![PixPin_2024-09-25_09-56-03](https://github.com/user-attachments/assets/de847b94-c3eb-4e02-8843-49b28f679c15)
应该是没有覆盖，新版本是从lemon这个仓库下载的

**Comment by ayangweb** [comment]
scoop 的安装包我不清楚是谁做的诶，能给我推一下吗？因为在周五发布的 0.1.0 有破坏性 bug，刚好破坏的就是数据库数据，我周六紧急修复并回退重新发布了版本！你这样，你先从 github下载 0.0.6，然后随便复制一些+收藏一些，然后从本站下载 0.1.0，然后再看看，我是专门修复了这个问题的！

**Comment by XylonMystic** [comment]
lemon    https://github.com/hoilc/scoop-lemon.git   2024/9/25 5:17:54       1260

好的，辛苦佬

**Comment by ayangweb** [comment]
好的，辛苦你帮忙测试下，然后给我反馈下！我这边发版前测试了几轮都是通过的！🌹

**Comment by XylonMystic** [comment]
我刚下载了0.0.6复制收藏了一些内容，升级到0.1.0 数据正常，收藏也都在

**Comment by ayangweb** [comment]
好的，那就是那个仓库是旧的0.1.0，还没有及时更新！🌹
