### ISSUE TITLE
[feat] 支持windows下免安装方式下载

### ISSUE THREAD

**Issue by bestv5** [EcoPasteHub/EcoPaste#580]
### Describe the problem

下载链接中不好区分平台，哪个是windows下免安装的包？

### Describe the solution you'd like

增加平台的标示，以增加标示度。或者增加windows平台下免安装包

**Comment by ayangweb** [comment]
windows 只有一个安装包，就是 .exe，如果 releases 比较难区分的话，可以认准 https://github.com/EcoPasteHub/EcoPaste?tab=readme-ov-file#windows，点击直接下载最新的稳定版本！

绿色包时打算等有缘的大佬支持的，软件目前已经支持了自定义存储路径，就不打算折腾绿色包了！
