### ISSUE TITLE
[bug] V0.1.0配置无法保存

### ISSUE THREAD

**Issue by Mabisi** [EcoPasteHub/EcoPaste#581]
### Describe the bug

设置数据库目录，已经开机自启，在重启电脑后都恢复默认了

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.1.0",
  "tauriVersion": "1.7.2",
  "platform": "Windows_NT",
  "platformArch": "x86_64",
  "platformVersion": "10.0.22631"
}
```

**Comment by ayangweb** [comment]
这个问题太奇怪了，每个版本都会收到，结果我们测试确一点问题没有！

你这个版本是从某个版本覆盖安装的？还是直接安装的 0.1.0！

**Comment by ayangweb** [comment]
0.0.6 没有出现偏好设置丢失的问题吗？

**Comment by Mabisi** [comment]
> 0.0.6 没有出现偏好设置丢失的问题吗？

0.0.6没有注意，我完全卸载重新安装0.1.0后 配置还是无法保存，数据目录还是恢复默认的C盘目录

**Comment by ayangweb** [comment]
很可能是 https://github.com/Noitidart/valtio-persist?tab=readme-ov-file#warning 这个问题！
