### ISSUE TITLE
[bug] macOS 测试安装报错

### ISSUE THREAD

**Issue by Kronight** [EcoPasteHub/EcoPaste#583]
### Describe the bug

=> brew tap EcoPasteHub/EcoPaste                                        🕙02:19

kronight ~
=> brew install ecopaste                                                🕙02:20
Warning: Cask 'ecopaste' is unreadable: /opt/homebrew/Library/Taps/ecopastehub/homebrew-ecopaste/Casks/ecopaste.rb:5: syntax error, unexpected <<
<<<<<<< HEAD
^~
/opt/homebrew/Library/Taps/ecopastehub/homebrew-ecopaste/Casks/ecopaste.rb:10: syntax error, unexpected ===
=======
^~~
/opt/homebrew/Library/Taps/ecopastehub/homebrew-ecopaste/Casks/ecopaste.rb:15: syntax error, unexpected >>
>>>>>>> 87d8a7c (v0.1.0)
^~
/opt/homebrew/Library/Taps/ecopastehub/homebrew-ecopaste/Casks/ecopaste.rb:15: unexpected fraction part after numeric literal
>>>>>>> 87d8a7c (v0.1.0)
                   ^~~~
/opt/homebrew/Library/Taps/ecopastehub/homebrew-ecopaste/Casks/ecopaste.rb:21: syntax error, unexpected <<
<<<<<<< HEAD
^~
==> Searching for similarly named formulae and casks...
Error: Cask 'ecopaste' is unreadable: /opt/homebrew/Library/Taps/ecopastehub/homebrew-ecopaste/Casks/ecopaste.rb:5: syntax error, unexpected <<
<<<<<<< HEAD
^~
/opt/homebrew/Library/Taps/ecopastehub/homebrew-ecopaste/Casks/ecopaste.rb:10: syntax error, unexpected ===
=======
^~~
/opt/homebrew/Library/Taps/ecopastehub/homebrew-ecopaste/Casks/ecopaste.rb:15: syntax error, unexpected >>
>>>>>>> 87d8a7c (v0.1.0)
^~
/opt/homebrew/Library/Taps/ecopastehub/homebrew-ecopaste/Casks/ecopaste.rb:15: unexpected fraction part after numeric literal
>>>>>>> 87d8a7c (v0.1.0)
                   ^~~~
/opt/homebrew/Library/Taps/ecopastehub/homebrew-ecopaste/Casks/ecopaste.rb:21: syntax error, unexpected <<
<<<<<<< HEAD
^~

kronight ~                                                                    1s
=>                                                                      🕙02:20

### Application and system information

```text
macOS 15
```

**Comment by ayangweb** [comment]
按照 https://github.com/EcoPasteHub/EcoPaste/issues/567#issuecomment-2367275324 试试！

**Comment by Kronight** [comment]
我先删除了，然后按照你的执行
```shell
kronight ~
=> brew uninstall --cask ecopaste ;brew untap ayangweb/EcoPaste         🕙14:20
Error: Cask 'ecopaste' is not installed.
Error: No available tap ayangweb/ecopaste.
Run brew tap-new ayangweb/ecopaste to create a new ayangweb/ecopaste tap!

kronight ~                                                                    1s
=> brew tap EcoPasteHub/EcoPaste;brew install ecopaste                  🕙14:21
Warning: Cask 'ecopaste' is unreadable: /opt/homebrew/Library/Taps/ecopastehub/homebrew-ecopaste/Casks/ecopaste.rb:5: syntax error, unexpected <<
<<<<<<< HEAD
^~
/opt/homebrew/Library/Taps/ecopastehub/homebrew-ecopaste/Casks/ecopaste.rb:10: syntax error, unexpected ===
=======
^~~
/opt/homebrew/Library/Taps/ecopastehub/homebrew-ecopaste/Casks/ecopaste.rb:15: syntax error, unexpected >>
>>>>>>> 87d8a7c (v0.1.0)
^~
/opt/homebrew/Library/Taps/ecopastehub/homebrew-ecopaste/Casks/ecopaste.rb:15: unexpected fraction part after numeric literal
>>>>>>> 87d8a7c (v0.1.0)
                   ^~~~
/opt/homebrew/Library/Taps/ecopastehub/homebrew-ecopaste/Casks/ecopaste.rb:21: syntax error, unexpected <<
<<<<<<< HEAD
^~
==> Searching for similarly named formulae and casks...
Error: Cask 'ecopaste' is unreadable: /opt/homebrew/Library/Taps/ecopastehub/homebrew-ecopaste/Casks/ecopaste.rb:5: syntax error, unexpected <<
<<<<<<< HEAD
^~
/opt/homebrew/Library/Taps/ecopastehub/homebrew-ecopaste/Casks/ecopaste.rb:10: syntax error, unexpected ===
=======
^~~
/opt/homebrew/Library/Taps/ecopastehub/homebrew-ecopaste/Casks/ecopaste.rb:15: syntax error, unexpected >>
>>>>>>> 87d8a7c (v0.1.0)
^~
/opt/homebrew/Library/Taps/ecopastehub/homebrew-ecopaste/Casks/ecopaste.rb:15: unexpected fraction part after numeric literal
>>>>>>> 87d8a7c (v0.1.0)
                   ^~~~
/opt/homebrew/Library/Taps/ecopastehub/homebrew-ecopaste/Casks/ecopaste.rb:21: syntax error, unexpected <<
<<<<<<< HEAD
^~

```

**Comment by ayangweb** [comment]
报错说是代码冲突了！但是很明显提交一切都是正常的！

重新 tap 一下试试：
```shell
brew untap EcoPasteHub/EcoPaste

brew tap EcoPasteHub/EcoPaste
```

<img width="1541" alt="image" src="https://github.com/user-attachments/assets/1ada4af0-5156-47bb-9671-7335a69a36fc">

**Comment by Kronight** [comment]
这样可以安装上
