### ISSUE TITLE
[bug] 托盘图标和快捷键以及窗口问题

### ISSUE THREAD

**Issue by witt-bit** [EcoPasteHub/EcoPaste#584]
### Describe the bug

Linux版有几个使用问题

1.无法设置快捷键为`Meta`开头的快捷键，比如`Meta + V` ,Meta就是Windows徽标键,因为Windows或Linux系统剪贴板管理的快捷键是`Meta + V`,我想设置成这个，替代系统

2.托盘图标上鼠标左键单击和右键单击效果一样，都是展示右键菜单，左键单击应该是打开剪贴板窗口

3.剪贴板窗口每次打开，都会跑到屏幕左上角，我是拓展显示器

4.剪贴板窗口无法在失去焦点后自动隐藏

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.1.0",
  "tauriVersion": "1.7.2",
  "platform": "Linux",
  "platformArch": "x86_64",
  "platformVersion": "24.0.8"
}
```

**Comment by ayangweb** [comment]
1、tauri 目前只有 MacOS 支持注册 `Meta` 组合快捷键，其它系统均需要使用其它 app 实现快捷键转发！
2、很遗憾，tauri 不支持！
<img width="627" alt="image" src="https://github.com/user-attachments/assets/2e5575d5-f37d-4c03-bc97-36665b91a4a1">
3 和 4 的问题 @AuroraTea 大佬最近正在排查修复！

**Comment by AuroraTea** [comment]
3和4和其它issue里提到的其实原因是一样的! 正在尝试修复! 4主要现在tauri的setFocus不知道为什么没用!

**Comment by ayangweb** [comment]
3. Duplicate of #596 
4. https://github.com/tauri-apps/tauri/issues/5620 关注看看这个 issue 了
