### ISSUE TITLE
[feat] AUR仓库支持

### ISSUE THREAD

**Issue by witt-bit** [EcoPasteHub/EcoPaste#586]
### Describe the problem

我提供了一个AUR软件包 https://aur.archlinux.org/packages/eco-paste-bin
供ArchLinux和Manjaro使用

### Describe the solution you'd like

期望使用github Action自动更新

**Comment by ayangweb** [comment]
佬，欢迎加入 [微信群](https://github.com/EcoPasteHub/EcoPaste?tab=readme-ov-file#%E5%8F%8D%E9%A6%88%E5%92%8C%E4%BA%A4%E6%B5%81) 详聊！
