### ISSUE TITLE
[bug] 隐藏托盘图标后再次打开，图标不显示

### ISSUE THREAD

**Issue by witt-bit** [EcoPasteHub/EcoPaste#587]
### Describe the bug

我先打开了"隐藏托盘图标"选项，图标隐藏了，然后我发现部分软件界面，无法使用快捷键打开界面，又想使用托盘图标,重新启动软件，关闭"隐藏托盘图标"选项,图标不再显示，重新安装也无效果，应该是需要删除缓存目录

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.1.0",
  "tauriVersion": "1.7.2",
  "platform": "Linux",
  "platformArch": "x86_64",
  "platformVersion": "24.0.8"
}
```

**Comment by witt-bit** [comment]
重新安装后，打开按钮，图标又显示了，也就是说，目前这个按钮只有在重新安装后，第一次点击，不管开关都是有效的

这两个菜单的名字太有歧义了   有什么区别
![image](https://github.com/user-attachments/assets/27421056-2749-4143-b17b-543c69080f8e)

**Comment by ayangweb** [comment]
以 mac 为例：

菜单栏图标就是托盘图标
<img width="386" alt="image" src="https://github.com/user-attachments/assets/ed6a2cf6-d713-421b-8e22-6465f4a2f95f">

任务栏图标就是程序坞图标
<img width="1550" alt="image" src="https://github.com/user-attachments/assets/0c513a17-38d5-4c60-8f65-d3cdc634452c">

**Comment by ayangweb** [comment]
这个问题是不在 0.2.0 可以了？

**Comment by witt-bit** [comment]
> 这个问题是不在 0.2.0 可以了？

0.2.0安装后打开就没有图标，打开关掉都不出现

**Comment by ayangweb** [comment]
那你截图去 tauri 提个 issue 问问吧！

**Comment by witt-bit** [comment]
应该是deb打包存在问题
https://github.com/tauri-apps/tauri/issues/11480
