### ISSUE TITLE
[bug] 富文本粘贴失效

### ISSUE THREAD

**Issue by Morganwan90** [EcoPasteHub/EcoPaste#588]
### Describe the bug

为什么我尝试复制了几个富文本都没有成功，如l录屏所示：

![recording](https://github.com/user-attachments/assets/d51c6f0a-2118-4f0e-bd76-25cb89db3bf4)

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.1.0",
  "tauriVersion": "1.7.2",
  "platform": "Windows_NT",
  "platformArch": "x86_64",
  "platformVersion": "10.0.22631"
}
```

**Comment by ayangweb** [comment]
<img width="730" alt="image" src="https://github.com/user-attachments/assets/e7051396-07fb-496d-b3cf-0bb6c8fabde9">

开一下是不是开了这个选项？

**Comment by ayangweb** [comment]
欢迎加入 [微信群](https://github.com/EcoPasteHub/EcoPaste?tab=readme-ov-file#%E5%8F%8D%E9%A6%88%E5%92%8C%E4%BA%A4%E6%B5%81) 详聊！

**Comment by Morganwan90** [comment]
可能是ditto和eco双开导致的...两个都关闭后，重新打开eco，恢复正常了。
感谢大佬 @ayangweb
