### ISSUE TITLE
[bug] Linux端无法粘贴

### ISSUE THREAD

**Issue by witt-bit** [EcoPasteHub/EcoPaste#589]
### Describe the bug

Linux端打开剪贴板，双击或单击后，会将文本复制到系统剪贴板（没有问题）

但是剪贴板打开的时候，光标被重新聚焦到了剪贴板的搜索栏，粘贴时，一直在搜索栏粘贴

![Uploading image.png…]()

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.1.0",
  "tauriVersion": "1.7.2",
  "platform": "Linux",
  "platformArch": "x86_64",
  "platformVersion": "24.0.8"
}
```

**Comment by witt-bit** [comment]
![image](https://github.com/user-attachments/assets/2db47aa5-62ee-4801-b956-08482dd074c0)

**Comment by witt-bit** [comment]
鼠标用不了，键盘方向键 ↑↓不能选择项目

**Comment by AuroraTea** [comment]
这个也还是focus的问题，不知道为什么即使加了appWindow.setFocus();也不能在呼出后让剪贴板获得焦点，比较奇怪的是在以前是可以的。

是focus的问题这点可以通过单击剪贴板后使用↑↓方向键来验证。

**Comment by witt-bit** [comment]
目前是双击后，能聚焦到上一个软件的输入框,但是出现上一个软件和EcoPaste相互抢占焦点的问题,且不能粘贴，同时引发系统任务栏高亮通知（新窗口会话消息提醒）

**Comment by ayangweb** [comment]
Duplicate of #28
