### ISSUE TITLE
[feat] 为剪贴板窗口添加标题栏和边框

### ISSUE THREAD

**Issue by witt-bit** [EcoPasteHub/EcoPaste#597]
### Describe the problem

深色模式下，剪贴板窗口在黑色的github网页上，分不清窗口边界

### Describe the solution you'd like

{
  "appName": "EcoPaste",
  "appVersion": "0.2.0-beta.1",
  "tauriVersion": "1.7.2",
  "platform": "Linux",
  "platformArch": "x86_64",
  "platformVersion": "24.0.8"
}

**Comment by ayangweb** [comment]
哦对，目前就 linux 不支持窗口阴影☹️
