### ISSUE TITLE
[feat] Linux下的数据存储目录应该在$HOME/.cache下

### ISSUE THREAD

**Issue by witt-bit** [EcoPasteHub/EcoPaste#598]
### Describe the problem

Linux数据和配置存储路径不正确
![image](https://github.com/user-attachments/assets/46104ed4-d719-4615-9d0d-09d750c381bb)

### Describe the solution you'd like

Linux下标准的数据存储应该在`$HOME/.config`
缓存应该在`$HOME/.cache`下

**Comment by ayangweb** [comment]
我用的 tauri 给的 [dataDir](https://tauri.app/v1/api/js/path/#datadir) 的目录！
