### ISSUE TITLE
[bug] win11家庭版中文版，安装后，无法使用，alt+c也没反应。双击软件，打开任务管理器，无运行程序

### ISSUE THREAD

**Issue by dmarkdmark** [EcoPasteHub/EcoPaste#601]
### Describe the bug

![Clip_2024-09-28_22-02-09](https://github.com/user-attachments/assets/60847d10-0af1-4ce1-bb33-c858c96524d5)

![Clip_2024-09-28_22-04-37](https://github.com/user-attachments/assets/4fc678a4-bd60-49a5-8d70-f277a3cb85a9)

### Application and system information

```text
nothing
```

**Comment by ayangweb** [comment]
你好，加入[微信群](https://github.com/EcoPasteHub/EcoPaste?tab=readme-ov-file#%E5%8F%8D%E9%A6%88%E5%92%8C%E4%BA%A4%E6%B5%81)看下问题吧

**Comment by dmarkdmark** [comment]
> 你好，加入[微信群](https://github.com/EcoPasteHub/EcoPaste?tab=readme-ov-file#%E5%8F%8D%E9%A6%88%E5%92%8C%E4%BA%A4%E6%B5%81)看下问题吧

1

**Comment by dmarkdmark** [comment]
![96b79aae6f2b5d0ed781b3bc708b856](https://github.com/user-attachments/assets/a446e923-26ca-4bc7-847e-0018aa507b3e)

出现问题原因：我卸载了Edge的Edg Webview（不喜欢Edge浏览器），下载回来就行了

往下拉，下这个

![Clip_2024-09-29_11-09-42](https://github.com/user-attachments/assets/7730b348-1d0d-4e85-a107-8ce0d4f3560f)

[下载常青独立安装程序](https://developer.microsoft.com/zh-cn/microsoft-edge/webview2/?form=MA13LH#download)
