### ISSUE TITLE
[feat] 打开剪贴板时候不要失去焦点

### ISSUE THREAD

**Issue by mmmmmmmgo** [EcoPasteHub/EcoPaste#605]
### Describe the problem

当我将焦点放到某个输入框时候,再用快捷键打开剪贴板时, 输入框的焦点丢失。

这个场景不常见,我说下的场景
比如我在用utools的ChatGPT好友时, utools打开的也是一个弹窗型窗口(失焦点窗口消失). 这时候我用快捷键打开这个弹窗时候, utools的窗口就隐藏了, 这个case, paste和pastenow都不会出问题.

### Describe the solution you'd like

打开剪贴板时候不失去焦点。

**Comment by ayangweb** [comment]
<img width="730" alt="image" src="https://github.com/user-attachments/assets/80461f14-dcf6-476e-b97d-aaf39414b121">

你说应该是这个

**Comment by mmmmmmmgo** [comment]
这里的搜索框是 剪贴板那边的搜索框吧

**Comment by mmmmmmmgo** [comment]
其实我希望焦点在这里
![image](https://github.com/user-attachments/assets/48c621de-8ebe-46d4-b601-9afc6145aa21)

**Comment by ayangweb** [comment]
Duplicate of #28
