### ISSUE TITLE
[feat] 快捷键设定

### ISSUE THREAD

**Issue by ggmood** [EcoPasteHub/EcoPaste#615]
### Describe the problem

可否设置为双击Ctrl？
这是最方便的按键位置和操作

### Describe the solution you'd like

可否设置为双击Ctrl？
这是最方便的按键位置和操作

**Comment by ayangweb** [comment]
Duplicate of #99

https://github.com/EcoPasteHub/EcoPaste/issues/99#issuecomment-2222166488
