### ISSUE TITLE
[feat] 按HOME键,滚动到顶部

### ISSUE THREAD

**Issue by mannfuri** [EcoPasteHub/EcoPaste#617]
### Describe the problem

处于列表中时,按键盘HOME键,滚动到顶部

### Describe the solution you'd like

处于列表中时,按键盘HOME键,滚动到顶部

**Comment by ayangweb** [comment]
好点子，不过我没有带 home 的键盘做测试，欢迎加入[微信群](https://github.com/EcoPasteHub/EcoPaste?tab=readme-ov-file#%E5%8F%8D%E9%A6%88%E5%92%8C%E4%BA%A4%E6%B5%81)，等我做了发群里帮忙试试！
