### ISSUE TITLE
[feat] 老哥，我想你是理解错我的意思了

### ISSUE THREAD

**Issue by xiawiner** [EcoPasteHub/EcoPaste#619]
### Describe the problem

希望这个软件的配置文件是保存在exe当前目录的，也就是所谓的便携版，这样对于那些安装了重启还原软件的用户来说很好，不然每次重启都要重新配置一遍，很麻烦。

### Describe the solution you'd like

希望可以增加这个功能，默认应该是保存在C盘了吧？毕竟每次重启我都要设置一遍~

**Comment by ayangweb** [comment]
Duplicate of https://github.com/EcoPasteHub/EcoPaste/issues/546#issuecomment-2363922431
