### ISSUE TITLE
[bug] 搜索时系统输入法被覆盖！

### ISSUE THREAD

**Issue by Suzzt** [EcoPasteHub/EcoPaste#621]
### Describe the bug

<img width="522" alt="image" src="https://github.com/user-attachments/assets/0f9a8607-f414-485e-9722-2e5e650a7906">
产品不错，希望继续迭代，加油～

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.1.0",
  "tauriVersion": "1.7.2",
  "platform": "Darwin",
  "platformArch": "x86_64",
  "platformVersion": "14.5.0"
}
```

**Comment by Suzzt** [comment]
系统为macos环境

**Comment by ayangweb** [comment]
我测试确实如此，我抽空看看啥情况！
