### ISSUE TITLE
[feat] 自定义收藏分类

### ISSUE THREAD

**Issue by Lotus6** [EcoPasteHub/EcoPaste#623]
### Describe the problem

只有个收藏不够用，自定义扩展加不同收藏标签

### Describe the solution you'd like

只有个收藏不够用，自定义扩展加不同收藏标签

### Alternatives considered

只有个收藏不够用，自定义扩展加不同收藏标签

### Additional context

只有个收藏不够用，自定义扩展加不同收藏标签

**Comment by ayangweb** [comment]
Duplicate of #145
