### ISSUE TITLE
[feat] 已粘贴过的条目用不同颜色显示（或其他不同标志）

### ISSUE THREAD

**Issue by feixd-up** [EcoPasteHub/EcoPaste#626]
### Describe the problem

当需要复制粘贴很多个文本时，一般是复制多个再粘贴多个，现在颜色一致，不容易区分哪些已经粘贴过了，希望可以使用不同颜色或其他不同来区分一下，谢谢作者，为你点赞

### Describe the solution you'd like

希望可以使用不同颜色或其他不同来区分一下已粘贴过的项目

**Comment by ayangweb** [comment]
好的，这个需求先保留，后续我们一起讨论讨论，可以加入[微信群](https://github.com/EcoPasteHub/EcoPaste?tab=readme-ov-file#%E5%8F%8D%E9%A6%88%E5%92%8C%E4%BA%A4%E6%B5%81)一起交流

**Comment by ayangweb** [comment]
这个需求不打算考虑🌹
