### ISSUE TITLE
[bug] 窗口无法拖动缩放

### ISSUE THREAD

**Issue by witt-bit** [EcoPasteHub/EcoPaste#627]
### Describe the bug

窗口最大化被禁用，但是在拓展屏上,屏幕比较大，设置项是可以在一屏放下的,但无法通过拖动改变窗口大小，仍然通过滚动条显示全部菜单
![image](https://github.com/user-attachments/assets/f7474901-9521-466f-9a50-21207ebddd34)

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.2.0-beta.2",
  "tauriVersion": "1.7.2",
  "platform": "Linux",
  "platformArch": "x86_64",
  "platformVersion": "24.1.0"
}
```

**Comment by ayangweb** [comment]
收到反馈，后续版本支持偏好设置窗口的缩放！
