### ISSUE TITLE
[feat] 输出文件路径的功能

### ISSUE THREAD

**Issue by zhymster** [EcoPasteHub/EcoPaste#629]
### Describe the problem

复制文件，在一些文本输入界面，点击还是会发送文件

### Describe the solution you'd like

复制文件，希望能在一些文本输入界面，输入复制文件的路径。使用和输出为纯文本同样的快捷键。

**Comment by ayangweb** [comment]
右键菜单给一个粘贴为路径的功能？这个功能只支持单个文件（夹）还是说多个文件（夹）用特定符号分开也支持？
