### ISSUE TITLE
[bug] 如视频所示,复制的内容保存不到你的软件中

### ISSUE THREAD

**Issue by Fowindy** [EcoPasteHub/EcoPaste#631]
### Describe the bug

具体现象可以观看这个链接的视频bug - https://www.wolai.com/fowindy/Thsm8Wwj9bxMBdH9FFb3q

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.2.0-beta.2",
  "tauriVersion": "1.7.2",
  "platform": "Windows_NT",
  "platformArch": "x86_64",
  "platformVersion": "10.0.19045"
}
```

**Comment by ayangweb** [comment]
<img width="210" alt="image" src="https://github.com/user-attachments/assets/704d1655-89a7-404a-a1b6-ef6704a9b750">

看下菜单栏是不是停止监听了！

**Comment by Fowindy** [comment]
没有停止监控，我后面复制其他的就可以的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ayang ***@***.***&gt;
发送时间: 2024年10月10日 17:52
收件人: EcoPasteHub/EcoPaste ***@***.***&gt;
抄送: Fowindy ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [EcoPasteHub/EcoPaste] [bug] 如视频所示,复制的内容保存不到你的软件中 (Issue #631)





 image.png (view on web) 
看下菜单栏是不是停止监听了！

**Comment by Fowindy** [comment]
绝大部分剪切板软件都有这个问题，只有那个很出名的没有这个问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ayang ***@***.***&gt;
发送时间: 2024年10月10日 17:52
收件人: EcoPasteHub/EcoPaste ***@***.***&gt;
抄送: Fowindy ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [EcoPasteHub/EcoPaste] [bug] 如视频所示,复制的内容保存不到你的软件中 (Issue #631)





 image.png (view on web) 
看下菜单栏是不是停止监听了！

**Comment by ayangweb** [comment]
你是说只有在 vs2015 复制有这个问题？

**Comment by Fowindy** [comment]
所有的都有这个问题，这个就好像是从界面复制就有这个问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ayang ***@***.***&gt;
发送时间: 2024年10月10日 18:10
收件人: EcoPasteHub/EcoPaste ***@***.***&gt;
抄送: Fowindy ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [EcoPasteHub/EcoPaste] [bug] 如视频所示,复制的内容保存不到你的软件中 (Issue #631)





 
你是说只有在 vs2015 复制有这个问题？

**Comment by Fowindy** [comment]
你可以试一下，很容易复现出来



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ayang ***@***.***&gt;
发送时间: 2024年10月10日 18:10
收件人: EcoPasteHub/EcoPaste ***@***.***&gt;
抄送: Fowindy ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [EcoPasteHub/EcoPaste] [bug] 如视频所示,复制的内容保存不到你的软件中 (Issue #631)





 
你是说只有在 vs2015 复制有这个问题？

**Comment by ayangweb** [comment]
我没太懂你说的意思，我是指你在 vs2015 复制内容的时候，EcoPaste 接收不到，但是其它例如微信这种复制可以正常接收？还是所有的软件都接收不到复制内容？

**Comment by Fowindy** [comment]
是什么意思呢？就是就是你那个VS也不是说VS 2015它接收不到，那个完全接收不到，不是这样的，是VS 2015到那个gate的那个界面，然后它你去详情里面，然后你这样去操作复制的时候它是接收不到的，然后VS如果说你到代码的那个界面去复制的话，它是可以接收到的。微信也可以接受到



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ayang ***@***.***&gt;
发送时间: 2024年10月10日 18:13
收件人: EcoPasteHub/EcoPaste ***@***.***&gt;
抄送: Fowindy ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [EcoPasteHub/EcoPaste] [bug] 如视频所示,复制的内容保存不到你的软件中 (Issue #631)





 
我没太懂你说的意思，我是指你在 vs2015 复制内容的时候，EcoPaste 接收不到，但是其它例如微信这种复制可以正常接收？还是所有的软件都接收不到复制内容？

**Comment by ayangweb** [comment]
哦哦，不分 vs 版本，如你视频操作就接收不到是吧，我有空试下，我没有 windows 电脑！☹️

**Comment by Fowindy** [comment]
是的其他的系统我不知道，反正Windows是有这个问题，我测试了很多这个软这种类型的软件吧，就一个。就一个软件它可以，其他的软件都不行。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ayang ***@***.***&gt;
发送时间: 2024年10月10日 18:21
收件人: EcoPasteHub/EcoPaste ***@***.***&gt;
抄送: Fowindy ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [EcoPasteHub/EcoPaste] [bug] 如视频所示,复制的内容保存不到你的软件中 (Issue #631)





 
哦哦，不分 vs 版本，如你视频操作就接收不到是吧，我有空试下，我没有 windows 电脑！☹️

**Comment by Fowindy** [comment]
还有那个文件夹的那个新功能的那个需求，你帮忙看一下，那个我觉得很有必要。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ayang ***@***.***&gt;
发送时间: 2024年10月10日 18:21
收件人: EcoPasteHub/EcoPaste ***@***.***&gt;
抄送: Fowindy ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [EcoPasteHub/EcoPaste] [bug] 如视频所示,复制的内容保存不到你的软件中 (Issue #631)





 
哦哦，不分 vs 版本，如你视频操作就接收不到是吧，我有空试下，我没有 windows 电脑！☹️

**Comment by ayangweb** [comment]
好

**Comment by ayangweb** [comment]
vs2022 跟你一样的操作，但是查看详情无法出现你那种界面！我是 arm64，所以找不到低版本适配的！

<img width="1758" alt="image" src="https://github.com/user-attachments/assets/d48cb4d8-010c-4d29-8505-b6898893a28c">

**Comment by Fowindy** [comment]
需要git,就是安装git




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月17日(星期四) 上午9:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [EcoPasteHub/EcoPaste] [bug] 如视频所示,复制的内容保存不到你的软件中 (Issue #631)














 
vs2022 跟你一样的操作，但是查看详情无法出现你那种界面！我是 arm64，所以找不到低版本适配的！
 image.png (view on web)

**Comment by Fowindy** [comment]
如果可以远程的话,我可以给搞出来




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月17日(星期四) 上午9:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [EcoPasteHub/EcoPaste] [bug] 如视频所示,复制的内容保存不到你的软件中 (Issue #631)














 
vs2022 跟你一样的操作，但是查看详情无法出现你那种界面！我是 arm64，所以找不到低版本适配的！
 image.png (view on web)

**Comment by ayangweb** [comment]
来吧，我没用过vs，给我搞一下

**Comment by ayangweb** [comment]
[微信群](https://github.com/EcoPasteHub/EcoPaste?tab=readme-ov-file#%E5%8F%8D%E9%A6%88%E5%92%8C%E4%BA%A4%E6%B5%81)联系我

**Comment by ayangweb** [comment]
EcoPaste 监听的是系统剪贴板变化，如果系统剪贴板都监听不到的话，那么 EcoPaste 也没办法！
