### ISSUE TITLE
[feat] 自动识别绝对路径并可右键打开路径

### ISSUE THREAD

**Issue by Fowindy** [EcoPasteHub/EcoPaste#632]
### Describe the problem

工作中经常会遇到常用的文件夹目录,我之前都会将这个目录的绝对路径复制下来,就会在剪切板里面记录了,等我下次需要打开这个文件夹,就将该路劲粘贴在资源管理器打开,这个过程完全可以通过你们软件来实现这个功能;

1. 你们可以后台识别一下是否是绝对路径(有特定的格式)
2. 是的话鼠标移过去可以右键有一个选项,打开目录,点击这个选项就自动打开这个文件夹了
3. 最好这个路径可以备注一个别名(就是容易看一点),
4. 目前看你们这里有文本,图片,文件等等,然后可以再开一个文件夹,这样就完美了

### Describe the solution you'd like

1. 你们可以后台识别一下是否是绝对路径(有特定的格式)
2. 是的话鼠标移过去可以右键有一个选项,打开目录,点击这个选项就自动打开这个文件夹了
3. 最好这个路径可以备注一个别名(就是容易看一点),
4. 目前看你们这里有文本,图片,文件等等,然后可以再开一个文件夹,这样就完美了

更详细的需求情况可以看这个视频:
功能需求 - https://www.wolai.com/fowindy/8f5RNxUDrUEMuKSSsgTZ7Y

**Comment by ayangweb** [comment]
好的，这个需求先保留，后续我想对文本类型进行大改动，会支持更多的类型！
