### ISSUE TITLE
[bug] linux 偏好设置窗口无法进行操作

### ISSUE THREAD

**Issue by witt-bit** [EcoPasteHub/EcoPaste#646]
### Describe the bug

TypeError: window['_' + 2174324376] is not a function. (In 'window['_' + 2174324376]({ message: response, id: 0 })', 'window['_' + 2174324376]' is undefined)
(anonymous function) — index.html:1:161

摁下快捷键Alt + X 报错
![image](https://github.com/user-attachments/assets/96305b21-acad-4ca3-b509-fa55170e783c)

点击设置按钮无响应
![image](https://github.com/user-attachments/assets/0d096a94-6d21-4dd9-8a90-5c84679e1082)

设置窗口一旦关闭  不能再打开

### Application and system information

```text
Linux
```

**Comment by ayangweb** [comment]
https://github.com/user-attachments/assets/a4ea8f27-33c9-4b99-a2c2-f53d9c179968

刚想去 tauri 提个 issue 问问，又发现忽然好了！你再试试
