### ISSUE TITLE
[bug] 多次摁下Alt + C 快捷键，窗口不响应，只有任务栏响应

### ISSUE THREAD

**Issue by witt-bit** [EcoPasteHub/EcoPaste#647]
### Describe the bug

多次摁Alt + C

![image](https://github.com/user-attachments/assets/ff98538f-7af4-41a4-9b64-67ef0eff9bd8)

### Application and system information

```text
linux
```

**Comment by ayangweb** [comment]
https://github.com/tauri-apps/tauri/issues/11323

**Comment by ayangweb** [comment]
Duplicate of #578
