### ISSUE TITLE
[bug] 剪贴板窗口出现位置总是在屏幕中间或上次的位置，未跟随光标

### ISSUE THREAD

**Issue by witt-bit** [EcoPasteHub/EcoPaste#648]
### Describe the bug

目前Linux下剪贴板窗口唤醒困难，出现位置不固定，建议先以普通窗口样式展示。先正常使用功能

### Application and system information

```text
Linux
```

**Comment by ayangweb** [comment]
这跟你说的什么普通窗口样式没关系，是 tauri 的 api 有问题！

[export interface SelectPayload extends TablePayload {}](https://github.com/tauri-apps/tauri/issues/11323)

**Comment by ayangweb** [comment]
Duplicate of #596

**Comment by witt-bit** [comment]
问题已解决，未开启跟随光标设置项
