### ISSUE TITLE
[bug] 粘贴为纯文本功能失效

### ISSUE THREAD

**Issue by howardhey** [EcoPasteHub/EcoPaste#661]
### Describe the bug

当前版本0.1.0，系统为win11专业版，配置了粘贴为纯文本的快捷键，在软件里看到设置成功，但是使用过程中无效，按这组快捷键后没有效果。

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.1.0",
  "tauriVersion": "1.7.2",
  "platform": "Windows_NT",
  "platformArch": "x86_64",
  "platformVersion": "10.0.22631"
}
```

**Comment by ayangweb** [comment]
我测试正常，把你的操作过程录个屏看看

**Comment by howardhey** [comment]
https://github.com/user-attachments/assets/179b87e6-c3eb-47cd-aefc-b092229fa48b

你好，我是设置了快捷键 ctrl+shift+v，ctrl+c复制后，用ctrl+shift+v快捷键粘贴不出来内容。请问是不是我没正确理解这个操作的逻辑或者对功能有误解，谢谢！

**Comment by ayangweb** [comment]
需要调出剪贴板窗口才可以粘贴纯文本（粘贴选中的），此快捷键不是全局的快捷键

**Comment by ayangweb** [comment]
Uploading iShot_2024-10-13_20.25.52.mp4…

**Comment by ayangweb** [comment]
https://github.com/user-attachments/assets/449f79ca-4407-476a-bff4-371ba5387588

**Comment by howardhey** [comment]
明白了，谢谢！
