### ISSUE TITLE
[feat] 交互过程优化

### ISSUE THREAD

**Issue by witt-bit** [EcoPasteHub/EcoPaste#663]
### Describe the problem

使用软件粘贴的流程大概如下：
1.目标窗口编辑
2.快捷键呼出剪贴板窗口
3.自动聚焦剪贴板窗口
4.鼠标或者键盘选择粘贴项
5.粘贴成功，隐藏剪贴板窗口

### Describe the solution you'd like

目前：
1.第三步缺失，呼出剪贴板窗口，焦点还在上个窗口
2.第四步，键盘无法选择剪贴板项目 ↑↓回车都无效，需要鼠标操作，但鼠标容易导致聚焦到上一个窗口时失效
3.第五步粘贴成功后，窗口未自动隐藏，此时焦点在父窗口，剪贴板窗口应该失去焦点自动关闭

**Comment by ayangweb** [comment]
所有后续问题都是 tauri 的 [`setFocus`](https://github.com/tauri-apps/tauri/issues/5620) 未能在 linux 生效导致的！

**Comment by ayangweb** [comment]
聚焦问题追踪：https://github.com/tauri-apps/tauri/issues/11395

**Comment by ayangweb** [comment]
KDE 参考：https://github.com/EcoPasteHub/EcoPaste/pull/660#issuecomment-2419888182

**Comment by Xiaobaishushu25** [comment]
> 所有后续问题都是 tauri 的 [`setFocus`](https://github.com/tauri-apps/tauri/issues/5620) 未能在 linux 生效导致的！

你好，请问是只有linux 不生效吗，我在windows上这样写：
```js
  const window = await WebviewWindow.getByLabel('record');
  if (window!=null){
    //todo bug https://github.com/tauri-apps/tauri/issues/6310
    console.log("窗口存在")
    await window.setFocus()//不起作用
    window.show()
    // await window.hide()
    // await window.show()
  }
```
发现也没有效果，是我写的不对吗。

**Comment by ayangweb** [comment]
@Xiaobaishushu25 linux 的 `setFocus` 无效! 

https://github.com/tauri-apps/tauri/issues/11395
