### ISSUE TITLE
[bug] 粘贴后，剪贴板条目改变bug

### ISSUE THREAD

**Issue by witt-bit** [EcoPasteHub/EcoPaste#664]
### Describe the bug

1.粘贴后，不管成功与否，如果选择的是除第一项的内容，后面的内容会迅速入栈为第一条，可能会导致窗口焦点问题(Linux)
2.粘贴后，如果选择的是除第一项的内容，后面的内容会迅速入栈为第一条，但选中的位置仍然是原来的位置，没有选择第一条

### Application and system information

```text
linux
```

**Comment by ayangweb** [comment]
跟粘贴无关，复制变位
