### ISSUE TITLE
[bug] 有时候唤醒在收藏页面但是显示内容是全部页面的

### ISSUE THREAD

**Issue by pheotry** [EcoPasteHub/EcoPaste#669]
### Describe the bug

有时候打开的时候收藏页面显示的全部的历史，需要切换一下才会刷新。
这里显示的并不是收藏的条目
![image](https://github.com/user-attachments/assets/49de6050-c9c1-496d-a567-7f712c723ffc)

### Application and system information

```text
版本	Windows 11 专业版
版本号	24H2
安装日期	‎2024/‎8/‎22
操作系统版本	26100.2152
体验	Windows Feature Experience Pack 1000.26100.32.0
```

**Comment by ayangweb** [comment]
fixed: https://github.com/EcoPasteHub/EcoPaste/releases/tag/v0.2.0-beta.1

**Comment by ayangweb** [comment]
下载 [v0.2.0-beta.1](https://github.com/EcoPasteHub/EcoPaste/releases/tag/v0.2.0-beta.1) 可正常使用！
