### ISSUE TITLE
[bug] 复制音效不生效

### ISSUE THREAD

**Issue by meimaodawang999** [EcoPasteHub/EcoPaste#683]
### Describe the bug

复制音效打开的前提下，复制的时候没有音效。

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.2.0-beta.3",
  "platform": "macos",
  "platformArch": "aarch64",
  "platformVersion": "15.0.1"
}
```

**Comment by ayangweb** [comment]
好的，我下来复现看看

**Comment by ayangweb** [comment]
这个我复现不了，找个机会我给发一个开发安装包，我们远程看看？

**Comment by ayangweb** [comment]
试一下最新的 [0.2.0](https://github.com/EcoPasteHub/EcoPaste/releases/tag/v0.2.0) 版本，看看是否有效

**Comment by ayangweb** [comment]
长时间未回复，我先关了，有问题再打开
