### ISSUE TITLE
[bug] 最新的测试版也无法保存配置

### ISSUE THREAD

**Issue by gitbruc** [EcoPasteHub/EcoPaste#688]
### Describe the bug

最新的测试版什么配置都保存不了，关闭再打开就全部消失
1.0版本可以保存快捷键，但是其他保存不了

### Application and system information

```text
win10专业版
```

**Comment by ayangweb** [comment]
<img width="730" alt="image" src="https://github.com/user-attachments/assets/a7be5af3-6441-465a-84f4-16b47f6d2766">

发 issue 带上完整的软件信息

**Comment by ayangweb** [comment]
你现在现在的是哪个版本？复制信息发出来

**Comment by gitbruc** [comment]
好的谢谢😎️
