### ISSUE TITLE
[bug] 设置无法保存，重启APP以后所有设置都丢失

### ISSUE THREAD

**Issue by Kenoncloud** [EcoPasteHub/EcoPaste#691]
### Describe the bug

设置无法保存，重启APP以后所有设置都丢失，681修复的beta版也不行

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.2.0-beta.3",
  "platform": "windows",
  "platformArch": "x86",
  "platformVersion": "10.0.26100"
}
```

**Comment by Kenoncloud** [comment]
能否采用ini文件的方式，把设置存档 在文件里，启动的时候读取配置文件

**Comment by ayangweb** [comment]
你的电脑是windows 32 位吗？

**Comment by Kenoncloud** [comment]
不是，64位的

**Comment by ayangweb** [comment]
下载 [EcoPaste_0.2.0-beta.3_x64-setup.exe](https://github.com/EcoPasteHub/EcoPaste/releases/download/v0.2.0-beta.3/EcoPaste_0.2.0-beta.3_x64-setup.exe) 正确的版本再重启试试！

**Comment by Kenoncloud** [comment]
试过了，一样的，刚重启完又没了
{
  "appName": "EcoPaste",
  "appVersion": "0.2.0-beta.3",
  "platform": "windows",
  "platformArch": "x86_64",
  "platformVersion": "10.0.26100"
}

**Comment by ayangweb** [comment]
<img width="730" alt="image" src="https://github.com/user-attachments/assets/c6529803-fa74-4d40-a5b1-94e330de67f9">

如果你没改数据存储路径，重启看这个目录里是否有隐藏文件 .store.json

**Comment by Kenoncloud** [comment]
![image](https://github.com/user-attachments/assets/60253721-f367-45f9-8d77-fe418db2013e)

**Comment by ayangweb** [comment]
重启有这个文件是吧？[微信群](https://github.com/EcoPasteHub/EcoPaste?tab=readme-ov-file#%E5%8F%8D%E9%A6%88%E5%92%8C%E4%BA%A4%E6%B5%81)加进来发我！

**Comment by Kenoncloud** [comment]
已发群

**Comment by ayangweb** [comment]
在 https://github.com/EcoPasteHub/EcoPaste/pull/689 中修复！我会尽快发布稳定版！
