### ISSUE TITLE
[feat] 希望加入静默启动

### ISSUE THREAD

**Issue by pheotry** [EcoPasteHub/EcoPaste#695]
### Describe the problem

就是启动的时候直接运行在后台，不弹出窗口

### Describe the solution you'd like

如上

**Comment by ayangweb** [comment]
事实上这已经是默认实现的功能，在你的电脑启动电脑也会显示出窗口？

**Comment by pheotry** [comment]
> 事实上这已经是默认实现的功能，在你的电脑启动电脑也会显示出窗口？

我的意思是双击图标启动时也可以支持一下这个功能，加个按钮

**Comment by ayangweb** [comment]
我懂了，不管何种启动方式，在首次启动都支持静默启动，这是一个很好的功能，我会很快实现它！
