### ISSUE TITLE
[bug] 导出数据错误

### ISSUE THREAD

**Issue by aurorax-neo** [EcoPasteHub/EcoPaste#703]
### Describe the bug

![image](https://github.com/user-attachments/assets/73696077-64dc-4e97-867f-6c751860c57c)

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.2.0",
  "platform": "windows",
  "platformArch": "x86_64",
  "platformVersion": "10.0.19045"
}
```

**Comment by ayangweb** [comment]
收到反馈，会和#668一起修复
