### ISSUE TITLE
[bug] macOS Sequoia 15.0.1版本下，应用全屏底下无法显示，只能在默认桌面显示。

### ISSUE THREAD

**Issue by L-Continue** [EcoPasteHub/EcoPaste#704]
### Describe the bug

RT，例如VSCODE或者其它软件全屏创建的新桌面中快捷键调出的界面只能出现在默认桌面，而不能在软件当前所在在桌面显示。

### Expected behavior

希望能解决在不同桌面的情况下显示，而不是要回到默认桌面去做相关操作。

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.2.0",
  "platform": "macos",
  "platformArch": "x86_64",
  "platformVersion": "15.0.1"
}
```

**Comment by ayangweb** [comment]
你说的应该是剪贴板窗口对吧？这个问题我已经知道咋解决了，但是会引起无法自动粘贴，所以还在研究！

**Comment by aihy** [comment]
+1
我只有一个显示器，IDE全屏工作时，相当于无法唤出剪贴板窗口了

**Comment by aihy** [comment]
开启跟随鼠标后好了。感谢





------------------ 原始邮件 ------------------
发件人: ayang ***@***.***&gt;
发送时间: 2024年11月29日 11:07
收件人: EcoPasteHub/EcoPaste ***@***.***&gt;
抄送: aihy ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [EcoPasteHub/EcoPaste] [bug] macOS Sequoia 15.0.1版本下，应用全屏底下无法显示，只能在默认桌面显示。 (Issue #704)





  
+1 我只有一个显示器，IDE全屏工作时，相当于无法唤出剪贴板窗口了
  
早就支持了，更新到 0.4.0 并开启窗口位置跟随鼠标了吗？
