### ISSUE TITLE
[feat] 根据按键自动搜索或轮询命中项

### ISSUE THREAD

**Issue by witt-bit** [EcoPasteHub/EcoPaste#707]
### Describe the problem

在Linux `Dolphin`（Windows 文件资源管理器也是）或者绝大多数其他类软件(例如jetbrians系列)，他们都有个特点，没有单独的搜索框，在任意位置，只要摁下文本类按键，就会开始搜索或者在首字母匹配的项目间轮询跳转

自动搜索
![Peek 2024-10-21 10-28](https://github.com/user-attachments/assets/de66a5ae-ae51-42f2-a7fe-7bf03a2f6cfd)

在按键时自动匹配首字母间跳转
![Peek 2024-10-21 10-30](https://github.com/user-attachments/assets/798256a7-4de0-4a43-a26c-334709f4f5c9)

现在Ecopaste在开启自动聚焦搜索框时是这样的
![Peek 2024-10-21 10-33](https://github.com/user-attachments/assets/18117093-fd16-4c40-b372-6ba5bf8bde77)

有几个我觉得使用上的问题，但不知道是不是这么设计的
1.快捷键打开后，直接输入内容就可以搜索，但是只要通过↑↓选择了内容,就需要鼠标聚焦搜索框才能搜索
2.如果先通过↑↓选择了内容,失去搜索框焦点了

### Describe the solution you'd like

1.我个人觉得焦点应该一直停留在搜索框,键盘↑↓选择了内容,输入文本仍然能继续搜索
2.直接通过输入文本过滤内容,在绝大部分情况下没有多大用处，剪贴板的内容是非常杂的，也是很乱的，可以参考
它是按顺序拆字符式的匹配
![Peek 2024-10-21 10-41](https://github.com/user-attachments/assets/62d6b7d3-a8f4-4e5e-a7bb-96ae6d4a7b42)

![image](https://github.com/user-attachments/assets/d92ad127-24c1-4553-a8b1-59d4ec21fe1b)

**Comment by ayangweb** [comment]
这个需求就不考虑了，在输入框内按上下回车等特殊的键是不会向上冒泡的，只能失去焦点才能操作，想要再次搜索，ctrl+f 就可以再次聚焦搜索框，纯键盘是可以操作的，不需要鼠标去聚焦！后期完整的写在文档里！

**Comment by ayangweb** [comment]
我觉得这个功能可以一试了🤔

**Comment by ayangweb** [comment]
大概实现了一个雏形，但是有个问题，中文输入法的问题！


https://github.com/user-attachments/assets/dd442359-00fc-484a-b76e-fc7d746dfa38

**Comment by ayangweb** [comment]
算了，由于中文输入法的问题，这个支持的不会很好！

**Comment by witt-bit** [comment]
> 大概实现了一个雏形，但是有个问题，中文输入法的问题！
> 
>  iShot_2024-11-17_19.15.39.mp4

我当时提的时候不是这么想的

1.不需要边输入边检索内容

2.不一定是全字匹配，搜索是分词匹配，例如"轮询命中项"   我当时想的是搜索 "轮询命中项" "轮询" "命中"  这样拆开的

3.按下字母数字键就开始搜索，`esc`出去,不需要我先点击搜索框才能开始搜索

**Comment by ayangweb** [comment]
那就是 `ctrf+f` 聚焦输入框。
