### ISSUE TITLE
[feat] 将历史记录保留时长改为保留最大条数

### ISSUE THREAD

**Issue by witt-bit** [EcoPasteHub/EcoPaste#708]
### Describe the problem

我理解保留时长的目的应该是防止存储过大，但是保留时长没有保留最大条数来的直接,比如 我设置保留最近7天,但是对于办公电脑，国庆长假这种，一个假期过去，剪贴板的所有内容就不见了

### Describe the solution you'd like

期望改为保留条数,这样设置保留100条，删除的永远是最久一直未使用的，超出这个条目数就删除了,都超过这个条数了，就不再需要了

**Comment by ayangweb** [comment]
好的，后续支持
