### ISSUE TITLE
[bug] 社区交流图片加载失败

### ISSUE THREAD

**Issue by XiCheng148** [EcoPasteHub/EcoPaste#711]
### Describe the bug

社区交流图片加载失败

<img width="700" alt="image" src="https://github.com/user-attachments/assets/0f558084-b784-4d2f-aba8-076ffcd67b3e">

### Software Information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.2.0",
  "platform": "macos",
  "platformArch": "aarch64",
  "platformVersion": "15.0.1"
}
```

**Comment by ayangweb** [comment]
<img width="730" alt="image" src="https://github.com/user-attachments/assets/fe33c7e4-2aae-4b64-a4e9-550306c81afe">

这会应该可以了！
