### ISSUE TITLE
[bug] win10更新报错

### ISSUE THREAD

**Issue by kilvn** [EcoPasteHub/EcoPaste#717]
### Describe the bug

首次点击更新按钮，过几秒报错
![image](https://github.com/user-attachments/assets/49ad7c49-51f1-4677-a2a7-742357005b82)

再次点击更新按钮，更新按钮无限转圈，然后就没有然后了。
![image](https://github.com/user-attachments/assets/0c43da0f-2d54-408c-b594-cdc20ea92b01)

### Software Information

```text
无
```

**Comment by ayangweb** [comment]
只能手动下载，自动更新有问题，下个版本修复！
