### ISSUE TITLE
[feat] 希望增加剪切板内增加多选操作快捷键等功能

### ISSUE THREAD

**Issue by chenp2436** [EcoPasteHub/EcoPaste#720]
### Describe the problem

1、剪切板内删除和收藏不能多选后操作 ，一个个操作有点费事，
2、还有就是红框内的操作 只能鼠标点击操作
![iShot_2024-10-22_16 25 27](https://github.com/user-attachments/assets/72d3b84c-31d8-4774-9f6e-0bce831ec133)

### Describe the solution you'd like

1、希望增加多选功能。
2、希望增加功能快捷键设置功能，方便快捷操作

**Comment by ayangweb** [comment]
1. Duplicate of #304 
2. 我会考虑

**Comment by ayangweb** [comment]
## 纯键盘操作

- 删除：`Backspace`
- 粘贴：`Enter`
- 收藏：`Ctrl + D`
- 粘贴为纯文本：自定义

常用的已支持，剩下的不常用的也就没有必要支持了！纯键盘操作未来会详细的写入官方网站里！
