### ISSUE TITLE
[bug] Windows安装包默认没有申请管理员权限导致安装失败

### ISSUE THREAD

**Issue by coulsonpl** [EcoPasteHub/EcoPaste#723]
### Describe the bug

Windows安装包在安装的时候一直报错，开始以为自己电脑的问题，后来试了一下使用管理员模式打开安装包就好了；所以安装包能否和其他软件一样，在安装之前先申请一下管理员权限，不然小白用户有点懵。系统: Win11 24H2

### Software Information

```text
v0.2.0
```

**Comment by ayangweb** [comment]
这个我得去看看有没有相关的上游的 issue 去了解了解！

**Comment by ayangweb** [comment]
在 #732 修复了此问题，欢迎随时加入[微信群](https://github.com/EcoPasteHub/EcoPaste?tab=readme-ov-file#%E5%8F%8D%E9%A6%88%E5%92%8C%E4%BA%A4%E6%B5%81)帮忙测试下测试版本是否可行！
