### ISSUE TITLE
[bug] 界面有点奇怪

### ISSUE THREAD

**Issue by XiCheng148** [EcoPasteHub/EcoPaste#738]
### Describe the bug

<img width="700" alt="图片" src="https://github.com/user-attachments/assets/94da3ef1-c2e9-4b11-b1de-bd8fcc16281d">

<img width="700" alt="图片" src="https://github.com/user-attachments/assets/12c7ffe8-b302-479f-a3c0-13eb445874ef">

打开发现界面颜色有点奇怪，关闭设置界面再打开也是这样的。大退软件再次打开不会了。

### Expected behavior

界面正常展示

### Software Information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.3.0-beta.2",
  "platform": "macos",
  "platformArch": "aarch64",
  "platformVersion": "15.0.1"
}
```

**Comment by ayangweb** [comment]
这个我也偶现，大概的问题是 css 未生效，这个无解，只能重启重新生效！
