### ISSUE TITLE
[feat] 希望简化列表

### ISSUE THREAD

**Issue by raining1123** [EcoPasteHub/EcoPaste#747]
### Describe the problem

我的电脑在微信和其他应用之间来回切换并复制粘贴内容时，经常出现复制失效的情况，需要一个简约的剪贴板用于查看复制是否成功

### Describe the solution you'd like

希望ecopaste能推出极简剪贴板列表，例如仅保留最近一个复制内容（倒数第二、第三做更小化处理）、内容之间的间距缩小、每个内容占据的方框行高减小等

**Comment by ayangweb** [comment]
听起来像是剪贴板堆栈功能？

**Comment by ayangweb** [comment]
Duplicate of #271 等支持
