### ISSUE TITLE
[bug] 当窗口位置选择屏幕中心时，拉伸窗口后，窗口无法被快捷键唤起

### ISSUE THREAD

**Issue by xpetrichor** [EcoPasteHub/EcoPaste#749]
### Describe the bug

当窗口位置选择屏幕中心时，拉伸窗口后，窗口无法被快捷键唤起

### Software Information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.3.0-beta.2",
  "platform": "windows",
  "platformArch": "x86_64",
  "platformVersion": "10.0.22631"
}
```

**Comment by ayangweb** [comment]
录屏看看！

**Comment by xpetrichor** [comment]
https://github.com/user-attachments/assets/b1c2470b-16f0-463a-a92d-d05679547ef1

大部分时候不能调用，但有些窗口尺寸又能调用，就比如说调到最小的时候就能调用
