### ISSUE TITLE
[bug] 双击全屏以后无法缩放回原尺寸

### ISSUE THREAD

**Issue by Kenoncloud** [EcoPasteHub/EcoPaste#753]
### Describe the bug

不小心双击全屏以后，再双击也无法回到小窗口。必须手动拉窗口尺寸
![screenshots](https://github.com/user-attachments/assets/9ce06a85-1d42-4717-b4a5-08da057eb399)

### Expected behavior

希望能增加一个一键还原默认尺寸，或者增加设置项，禁止双击窗口变大

### Software Information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.2.0",
  "platform": "windows",
  "platformArch": "x86_64",
  "platformVersion": "10.0.26100"
}
```

**Comment by ayangweb** [comment]
fixed: #730
