### ISSUE TITLE
[bug] 无限在线更新

### ISSUE THREAD

**Issue by Couleur-Share** [EcoPasteHub/EcoPaste#757]
### Describe the bug

这个在线更新怎么感觉一直都不好使啊，点击更新，更新后打开还是旧版本

### Software Information

```text
这个在线更新怎么感觉一直都不好使啊，点击更新，更新后打开还是旧版本
```

**Comment by ayangweb** [comment]
fixed: https://github.com/EcoPasteHub/EcoPaste/pull/702
