### ISSUE TITLE
[feat] 希望能够增加预览视窗和段落选中复制

### ISSUE THREAD

**Issue by xpetrichor** [EcoPasteHub/EcoPaste#760]
### Describe the problem

有时候复制的文本太长导致后面的内容无法查看，有时候只需要粘贴其中的一小节

### Describe the solution you'd like

希望能支持左右视窗分栏预览，左边是条目，右边是预览窗口，或者反过来或者是上下，然后中间的分栏是可以拉动的。
希望能支持选中段落内容再复制
像是这样

https://github.com/user-attachments/assets/1f6c48ea-68df-4d65-b002-23eb2be16cd3

**Comment by ayangweb** [comment]
Duplicate of #71 等支持
