### ISSUE TITLE
[bug] [bug] 0.3.0版本无法唤出偏好设置页面

### ISSUE THREAD

**Issue by iaw-dlay** [EcoPasteHub/EcoPaste#761]
### Describe the bug

从0.3.0-beta3升级到0.3.0正式版本之后，剪贴板窗口正常，但是点击剪贴板窗口右上角的齿轮图标后无法唤出。然后打算回退到0.3.0-beta3版本，但是发现这一版本也发生了无法打开偏好设置的问题，接着是尝试回退到0.3.0-beta2、0.3.0-beta1、0.2.0版本，结果均无法打开设置页面（之前使用这几个版本的时候没有发生过这种问题）

### Software Information

```text
无法打开设置页面故无法复制软件信息
```

**Comment by ayangweb** [comment]
完全卸载重新安装试试吧

**Comment by iaw-dlay** [comment]
> 完全卸载重新安装试试吧

之前试过好几次完全卸载重装，但是问题还是照旧
不过尝试在删除了用户数据之后发现0.3.0版本可以正常打开设置界面了，补一下软件信息
{
  "appName": "EcoPaste",
  "appVersion": "0.3.0",
  "platform": "windows",
  "platformArch": "x86_64",
  "platformVersion": "10.0.19045"
}

然后我最开始升级0.3.0之后因为没有通过软件导出backup备份数据，现在是把数据存储路径下面的EcoPaste.db替换成了之前删除的数据，看了一下剪贴板复制的内容还在，就只是软件里的个人设置重置成默认设置了

**Comment by ayangweb** [comment]
嗯，目前这个问题还不知道什么引起的，部分用户需要卸载重装就好了！
