### ISSUE TITLE
[bug] 当复制以特定字符开头的内容时不会在剪贴板上显示

### ISSUE THREAD

**Issue by iaw-dlay** [EcoPasteHub/EcoPaste#763]
### Describe the bug

尝试了几个复制结果，目前发现有两种情况会导致剪贴板不显示复制结果（而且复制时没有音效，但是粘贴时是可以正常粘贴的）：

- **以两个以上的字母**+“**:**”（半角冒号）开头，
- **以两个以上的字母**+**任意数量的数字**+“**:**”（半角冒号）开头，

另外，在这两种开头的前面加空格的时候也会发生一样的情况

### Reproduction

比如复制这几个内容就不会在剪贴板上显示：
apple:banana
apple123:banana
      apple:banana
      apple123:banana
（下面两个字符的前面有空格）

而这些则可以显示：
e:banana
apple：banana  （这里是全角冒号）
123apple:banana
苹果apple:banana
#@￥apple:banana
123:banana

### Software Information

```text
"appName": "EcoPaste",
  "appVersion": "0.3.0",
  "platform": "windows",
  "platformArch": "x86_64",
  "platformVersion": "10.0.19045"
```

**Comment by ayangweb** [comment]
和 https://github.com/EcoPasteHub/EcoPaste/pull/759 是同一个问题，等下次发版🌹
