### ISSUE TITLE
[bug] windows上有些时候会丢失焦点，导致选中复制无法直接粘贴进去

### ISSUE THREAD

**Issue by wekerSnail** [EcoPasteHub/EcoPaste#765]
### Describe the bug

在某些情况下，呼出剪切板，选中文本无法直接粘贴进输入框，因为焦点丢失，不是每次出现，但是出现的概率很高

### Software Information

```text
v0.3.0-beta.3
```

**Comment by ayangweb** [comment]
录个屏吧，顺便把完整的软件信息复制过来！

<img width="730" alt="image" src="https://github.com/user-attachments/assets/b1264efc-d594-45d3-b966-fd642c0f2780">

**Comment by wekerSnail** [comment]
在我遇到的那个情况，我不知道怎么稳定复现，不过在视频里这个场景可以稳定复现，估计是类似的问题
{
  "appName": "EcoPaste",
  "appVersion": "0.3.0-beta.3",
  "platform": "windows",
  "platformArch": "x86_64",
  "platformVersion": "10.0.22631"

https://github.com/user-attachments/assets/9f39acfa-0cc6-4599-9080-5600ed15f976


}

**Comment by ayangweb** [comment]
Duplicate of #28 

等支持
