### ISSUE TITLE
[bug] 保存剪贴板条目时简单过滤

### ISSUE THREAD

**Issue by witt-bit** [EcoPasteHub/EcoPaste#768]
### Describe the bug

我的剪贴板中有一些空白数据和一些重复数据，是隔一段时间可能重复复制了,希望有一个简单的过滤规则,在保存的时候直接丢弃

1.空白数据直接不要了
2.多次复制同一个内容，仅将内容置顶到第一项，不再重复保存

比如我是开发，经常复制一些数据的id,这些id很长记不住，过一会就得去重新复制，剪贴板里很快就很多内容了

### Software Information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.3.0",
  "platform": "linux",
  "platformArch": "x86_64",
  "platformVersion": "24.1.1"
}
```

**Comment by ayangweb** [comment]
如果是开发过程中，复制多条属于正常情况，我也这样，startListen 被多次执行了而已，这无所谓，生成环境不会出现！

**Comment by ayangweb** [comment]
空白数据保留吧！
