### ISSUE TITLE
[bug] 无法定位程序输入点 FrocessFrng 于动态链接库 beryptprimitives.dll

### ISSUE THREAD

**Issue by volansz** [EcoPasteHub/EcoPaste#773]
### Describe the bug

切换“全部”“文本”。。。等标签后，复制的文本内容变成了“无法定位程序输入点 FrocessFrng 于动态链接库 beryptprimitives.dll”

### Software Information

```text
v0.4.0-beta.1
```

**Comment by ayangweb** [comment]
没截图？

复制的软件信息呢？

**Comment by volansz** [comment]
![1](https://github.com/user-attachments/assets/d33ff0a8-eada-4477-a5db-60b6824d1aa7)
我彻底卸载（包括数据文件+注册表）后，现在正常了。
看来是数据文件出了问题。

**Comment by volansz** [comment]
![1](https://github.com/user-attachments/assets/3d54f703-61f6-4e81-a54c-c046c12cc08f)
出问题后我退回到0.3.0了，不能复现那个问题了。
我彻底卸载（包括数据文件+注册表）后，再安装0.4.0，现在正常了。
看来是数据文件出了问题。

**Comment by ayangweb** [comment]
奇怪了，每次更新，windows 的小部分电脑总能给人惊喜😂好了就行
