### ISSUE TITLE
[feat] 能否增加收藏分组和使用webdav进行多设备同步

### ISSUE THREAD

**Issue by Firfr** [EcoPasteHub/EcoPaste#793]
### Describe the problem

能否增加对收藏夹内容设置分组，和使用webdav进行多设备同步

### Describe the solution you'd like

能否增加对收藏夹内容设置分组，在收藏的内容较多的时候，可以快速找出内容，方便有较多的收藏内容时进行管理  

能否增加使用webdav进行多设备同步，这样就可以在对设备上同步剪切板内容  
考虑到数据的大小，可以按需选择要同步的内容，比如只同步文本，且只同步收藏夹中的内容

**Comment by ayangweb** [comment]
分组：Duplicate of #145 
云同步：Duplicate of #62 

等支持！

**Comment by coverthesea** [comment]
这个也是我初步接触这个软件，最需要的功能
