### ISSUE TITLE
[feat] 增加对键盘编辑区按键的支持

### ISSUE THREAD

**Issue by nuotu** [EcoPasteHub/EcoPaste#794]
### Describe the problem

增加insert、delete、home、end、pageUp、pageDown支持，提高操作效率

### Describe the solution you'd like

翻页、切换标签等

**Comment by ayangweb** [comment]
delete、home、pageUp、pageDown 你试过了没生效？

**Comment by nuotu** [comment]
> delete、home、pageUp、pageDown 你试过了没生效？delete、home、pageUp、pageDown 你试过了没生效？delete、home、pageUp、pageDown 你试过了没生效？
> 
> enter 粘贴，这些都是已经支持的功能enter 粘贴，这些都是已经支持的功能 enter 粘贴，这些都是已经支持的功能

没有反应，我以为不支持的

**Comment by ayangweb** [comment]
录个你操作的屏幕吧（随便找一款按键显示工具），这些我们都测试过没问题的！

**Comment by ayangweb** [comment]
https://github.com/user-attachments/assets/50157e70-e2f7-4e1e-9e89-a2a9beeb73ef

我键盘没有 `home` 键，没法测试，朋友测过是正常可以回到顶部的！

**Comment by ayangweb** [comment]
长时间未回复，我先关了，有问题我会重新打开！
