### ISSUE TITLE
[bug] 剪贴板弹窗界面尺寸异常

### ISSUE THREAD

**Issue by gears233** [EcoPasteHub/EcoPaste#795]
### Describe the bug

截图高度为完整电脑屏幕的高度，使用快捷键呼出剪贴板，弹出窗口高度异常，界面溢出屏幕高度。

可能有助于排查的额外信息：电脑同时连接了显示器作为拓展屏幕，左右并排排列屏幕使用。

<img width="1181" alt="image" src="https://github.com/user-attachments/assets/aff5a89f-be2d-4fca-a79e-d4a8b7f0d88f">

### Expected behavior

剪贴板高度限定为不超过当前屏幕大小

### Software Information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.3.0",
  "platform": "macos",
  "platformArch": "aarch64",
  "platformVersion": "15.1.0"
}
```

**Comment by ayangweb** [comment]
<img width="1106" alt="iShot_2024-11-12_10 17 23" src="https://github.com/user-attachments/assets/b3ea20ec-e055-4b24-ba2d-66e51efeec8a">

然后录个复现视频看看！

**Comment by ayangweb** [comment]
忘了说，需要重启才能生效！

**Comment by ayangweb** [comment]
嗯嗯，窗口不建议拉得太大，我们后续会加入精简列表，会显示更多的内容！
