### ISSUE TITLE
[bug] 我崩溃了啊，数据存储路径是干嘛用的？

### ISSUE THREAD

**Issue by txl263** [EcoPasteHub/EcoPaste#796]
### Describe the bug

我把默认的数据存储路径放到系统盘外，然后今天系统重装后我把默认的数据存储路径改成了之前设置过的位置。
然后你猜发生了什么？剪贴板历史是空的！玩呢？

### Reproduction

玩呢？

### Expected behavior

玩呢？

### Software Information

```text
玩呢？
```

**Comment by ayangweb** [comment]
不要慌，加一下readme的微信群，BTW，你下载的啥版本？

**Comment by txl263** [comment]
> 不要慌，加一下首页的微信群探讨下，BTW，你下载的啥版本？

Win11 v0.2.0
我看都出0.4beta了，它居然自己没更新

**Comment by txl263** [comment]
版本显示有个小bug
![image](https://github.com/user-attachments/assets/88326391-793b-4928-898a-acdce8a5322a)
![image](https://github.com/user-attachments/assets/c1fb11b9-bc89-4790-9026-d6fadf33521a)

**Comment by txl263** [comment]
> 不要慌，加一下首页的微信群探讨下，BTW，你下载的啥版本？

烦呢，我看了下数据库文件，被覆盖了。。。
我想打死那个做概要设计的，数据覆盖居然不提示！

**Comment by ayangweb** [comment]
![image](https://github.com/user-attachments/assets/5a50094e-fb59-4534-822b-92f08a26046b)

我理解你可能对软件更新或某些问题感到不满，但请保持冷静，不要把个人情绪带到这里。我们是一个开源项目，团队成员都在尽力帮助用户解决问题。如果你有任何问题或建议，欢迎随时提出。请记住，这不是付费项目。

**Comment by fzlzjerry** [comment]
> > 不要慌，加一下首页的微信群探讨下，BTW，你下载的啥版本？
> 
> 烦呢，我看了下数据库文件，被覆盖了。。。 我想打死那个做概要设计的，数据覆盖居然不提示！ 然后，微信二维码过期了

e，毕竟这是开源的项目，有bug正常，至少开发者愿意提供这种免费的软件而不是要求付费，毕竟这种剪贴板软件基本都是要付费的

**Comment by txl263** [comment]
> > > 不要慌，加一下首页的微信群探讨下，BTW，你下载的啥版本？
> > 
> > 
> > 烦呢，我看了下数据库文件，被覆盖了。。。 我想打死那个做概要设计的，数据覆盖居然不提示！ 然后，微信二维码过期了
> 
> e，毕竟这是开源的项目，有bug正常，至少开发者愿意提供这种免费的软件而不是要求付费，毕竟这种剪贴板软件基本都是要付费的

bug可以接受，但是这种设计缺陷出现不应该，概要设计还是重新捋捋吧，Windows平台覆盖没提示那Mac平台是不也没有

**Comment by ayangweb** [comment]
如果遇到问题或有需求，随时提出来，我们都会积极帮助解决。不必在这里发泄情绪，这里不是你家，没人惯着你。跟你说人话你就听，非得找骂，用户这么多，我们要围着你一个人转？就是你这种人一天天的把开源社区弄臭的！

**Comment by fzlzjerry** [comment]
> > > > 不要慌，加一下首页的微信群探讨下，BTW，你下载的啥版本？
> > > 
> > > 
> > > 烦呢，我看了下数据库文件，被覆盖了。。。 我想打死那个做概要设计的，数据覆盖居然不提示！ 然后，微信二维码过期了
> > 
> > 
> > e，毕竟这是开源的项目，有bug正常，至少开发者愿意提供这种免费的软件而不是要求付费，毕竟这种剪贴板软件基本都是要付费的
> 
> bug可以接受，但是这种设计缺陷出现不应该，概要设计还是重新捋捋吧，Windows平台覆盖没提示那Mac平台是不也没有

是谁惯着你这臭脾气的😅，有bug就冷静的说谁惯着你的，用不惯就别用
