### ISSUE TITLE
[bug] 复制的内容软件中没有

### ISSUE THREAD

**Issue by Firfr** [EcoPasteHub/EcoPaste#803]
### Describe the bug

有时候复制的文字，软件中不展示，无论是快捷键复制和右键复制，都没有，将文字粘贴到vscode，在复制，软件中还是没有
系统信息
设备名称	Win11-PVE
处理器	12th Gen Intel(R) Core(TM) i5-12400   2.50 GHz
机带 RAM	12.0 GB
设备 ID	F290ACD6-FE12-4677-9BE3-1EFE5BCF2D54
产品 ID	00425-00000-00002-AA786
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入

![2024-11-13_00-10-34](https://github.com/user-attachments/assets/084ec610-8f8b-4808-b79b-37f1fe4e371d)

### Software Information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.3.0",
  "platform": "windows",
  "platformArch": "x86_64",
  "platformVersion": "10.0.26100"
}
```

**Comment by ayangweb** [comment]
有试过卸载重装吗？加入[微信群](https://github.com/EcoPasteHub/EcoPaste?tab=readme-ov-file#%E5%8F%8D%E9%A6%88%E5%92%8C%E4%BA%A4%E6%B5%81)发一下日志看看吧！

**Comment by ayangweb** [comment]
Resolved #759
