### ISSUE TITLE
[bug] win11 开机启动后会卡主，不记录剪切板，左键点击和快捷键都没反应，需要右键点出，然后就正常工作了

### ISSUE THREAD

**Issue by desperad00** [EcoPasteHub/EcoPaste#804]
### Describe the bug

机启动后会卡主，不记录剪切板，左键点击和快捷键都没反应，需要右键点出，然后就正常工作了

### Software Information

```text
最近版本010
```

**Comment by ayangweb** [comment]
需要完整信息
<img width="730" alt="image" src="https://github.com/user-attachments/assets/62df0b31-7223-4208-bc81-a0ff60d95f69">

**Comment by ayangweb** [comment]
长时间不回复，我先关了，有问题再反馈
