### ISSUE TITLE
[bug] 重启后版本自动回退

### ISSUE THREAD

**Issue by code-zero640** [EcoPasteHub/EcoPaste#808]
### Describe the bug

装了0.3.0后，重启电脑还是为0.2提示需要更新0.3.0，再次安装时显示0.3已安装，这几天都是这样
<img width="527" alt="微信图片_20241115103236" src="https://github.com/user-attachments/assets/94409583-b0f5-4743-99c7-5cc556ed16c3">
<img width="375" alt="微信图片_20241115103248" src="https://github.com/user-attachments/assets/433f0169-b8d0-4427-9d8a-60825b191aee">

### Software Information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.2.0",
  "platform": "windows",
  "platformArch": "x86",
  "platformVersion": "10.0.22635"
}
```

**Comment by ayangweb** [comment]
找到电脑里的 0.2.0 卸载掉，有两个版本！
