### ISSUE TITLE
[feat] 托盘右键菜单添加重启项

### ISSUE THREAD

**Issue by witt-bit** [EcoPasteHub/EcoPaste#809]
### Describe the problem

Linux下是无法使用软件内部的自动更新的，只能自己下载更新或使用包管理器更新

但更新后，软件无法感知，只能手动退出，再打开

### Describe the solution you'd like

建议添加重启菜单，直接重启程序

**Comment by ayangweb** [comment]
加在哪个位置合适？退出前面吗

**Comment by witt-bit** [comment]
> 加在哪个位置合适？退出前面吗

没问题   各个软件都这么假的,你可以统一4个字


退出应用
重启应用
