### ISSUE TITLE
[feat] 剪贴板内容右上方操作按钮自定义

### ISSUE THREAD

**Issue by pscq0724** [EcoPasteHub/EcoPaste#810]
希望剪贴板内容右上方选项可自定义添加，参考PixPin那样添加可定制选项
![PixPin_2024-11-15_17-11-24](https://github.com/user-attachments/assets/b93bc325-d776-4afd-acdc-7ecf6d9484c3)

**Comment by ayangweb** [comment]
好的，抽空安排一下
