### ISSUE TITLE
[bug] 激活窗口时，“自动滚到顶部”机能导致鼠标滚轮无法激活滚动条

### ISSUE THREAD

**Issue by mannfuri** [EcoPasteHub/EcoPaste#813]
### Describe the bug

问题描述：

Widnows10

快捷键激活窗体后，都不点击窗体，只用鼠标中键做滚动操作的话，这次打开你能滚动，ESC关掉窗体后，再激活窗体，你就无法滚动了，以此类推，单数不响应，双数响应。

再现方式：

每次激活窗口，都只滚动滚轮，不点击左键。

https://github.com/user-attachments/assets/d2e29ef5-d0ce-441b-b8f2-00c8e37195fc

### Software Information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.4.0",
  "platform": "windows",
  "platformArch": "x86_64",
  "platformVersion": "10.0.19045"
}
```

**Comment by mannfuri** [comment]
经过我测试，从v0.0.1开始，这个BUG就有了

**Comment by uqiu** [comment]
```
#IfWinActive ahk_exe EcoPaste.exe
~!`::
    Send, {ESC}
#ifwinactive
```

经过我的测试，如果是用ESC键来退出窗口的话，再次呼出是可以正常聚焦和滚动的。
所以用上述AHK可破这个问题。
!`是你自己定义的呼出快捷键。

**Comment by ayangweb** [comment]
创建新项目，试试 alt 开头的组合键是否可行，如果不可行，那么就是 tauri 的锅🤔

**Comment by ayangweb** [comment]
这个问题长时间未回复，我先关了！
