### ISSUE TITLE
[bug] 滑动粘贴列表会报错

### ISSUE THREAD

**Issue by Klastin** [EcoPasteHub/EcoPaste#817]
### Describe the bug

向下滑动就会报错
![PixPin_2024-11-17_13-48-15](https://github.com/user-attachments/assets/cfa42e36-54ac-4de1-a318-057928efea2b)

### Software Information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.4.0",
  "platform": "windows",
  "platformArch": "x86_64",
  "platformVersion": "10.0.26100"
}
```

**Comment by ayangweb** [comment]
可以试试卸载重装，还不行的加入[微信群](https://github.com/EcoPasteHub/EcoPaste?tab=readme-ov-file#%E5%8F%8D%E9%A6%88%E5%92%8C%E4%BA%A4%E6%B5%81)，发个日志看看

**Comment by ayangweb** [comment]
由于长时间未收到回复，此 issue 将被关闭。您可以尝试通过 **uninstall.exe** 卸载应用后，重新安装最新版本进行解决！
