### ISSUE TITLE
[bug] Linux下按键失效

### ISSUE THREAD

**Issue by witt-bit** [EcoPasteHub/EcoPaste#821]
### Describe the bug

之前是可用的，现在`Home` 、  `End` 、  `PgUp`、  `PgDown`   、`Ctrl + Home`  、`Ctrl + End`安全都没用了

### Software Information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.4.0",
  "platform": "linux",
  "platformArch": "x86_64",
  "platformVersion": "24.1.2"
}
```

**Comment by ayangweb** [comment]
这些快捷键除了 `Home`键，其它的我没有主动设置，是 `WebKitGTK` 的默认行为
