### ISSUE TITLE
[bug] 0.4版本  win10 LTSC 无法打开设置面板

### ISSUE THREAD

**Issue by Kenoncloud** [EcoPasteHub/EcoPaste#822]
### Describe the bug

升级了0.4版本后（先卸载后升级），无法打开设置面板，无论是快捷键还是右键都没反应，复制粘贴没有问题。

### Software Information

```text
Microsoft Windows
版本 21H2(操作系统内部版本 19044.5131)© Microsoft Corporation。保留所有权利。
Windows 10 loT 企业版 LTSC 操作系统及其用户界面受美国和其他国家/地区的商标法和其他待颁布或已颁布的知识产权法保护。
```

### Additional context

![screenshots](https://github.com/user-attachments/assets/3ba4b7b2-e456-498b-9314-a4fa41fccd98)

**Comment by ayangweb** [comment]
删掉数据存储目录的 .window-state.json 文件，然后重启！
