### ISSUE TITLE
[feat] 希望激活剪贴窗口可以默认到【全部】按钮 

### ISSUE THREAD

**Issue by ZhouMoon** [EcoPasteHub/EcoPaste#823]
### Describe the problem

- 当我选择完【收藏】按钮里的内容并关闭窗口，再次激活剪贴窗口，需要用鼠标点击【全部】按钮。是不是可以分配几个快捷键、或者可以通过Tab键切换.

### Describe the solution you'd like

可以分配几个快捷键，激活窗口时生效

**Comment by ZhouMoon** [comment]
- 其实光标没有聚焦到【搜索】框时用hjkl切换上下及左右切换tab挺好，或者上下左右键也行。

**Comment by ayangweb** [comment]
我会添加配置项来实现这个功能，分组切换的按键我还在考虑，上下左右已经被剪贴板内容征用了
