### ISSUE TITLE
[bug] 暗黑模式下HTML文字看不清

### ISSUE THREAD

**Issue by AprDeci** [EcoPasteHub/EcoPaste#832]
### Describe the bug

如图,灰字白底看不清楚
![image](https://github.com/user-attachments/assets/4df868f5-25cf-435e-81cf-4c0c49f8768d)

### Software Information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.4.0",
  "platform": "windows",
  "platformArch": "x86_64",
  "platformVersion": "10.0.19044"
}
```

**Comment by ayangweb** [comment]
这与复制的内容有关，我们无法进行修改，复制是什么颜色就呈现什么颜色！
