### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by kisszoe2017** [EcoPasteHub/EcoPaste#838]
### Describe the bug

![PixPin_2024-11-24_10-47-28](https://github.com/user-attachments/assets/2fbe0b61-049b-4922-be73-882d51afe5ca)
打开设置无反应后多次点击就会出现关不掉的透明框（win11 24h ）重启程序也无法关闭，后续请关注一下该问题，感谢开发者和所有贡献者

### Software Information

```text
无
```

**Comment by ayangweb** [comment]
fixed #835
