### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by David-design352** [EcoPasteHub/EcoPaste#840]
### Describe the bug

win11 24h2，EcoPaste有时会打不开程序界面（快捷键也失灵了，结束资源占用才能关掉）使用的是最新版，每次打开都会重置快速粘贴界面大小（希望加入记忆）感谢开发者和贡献者
![image](https://github.com/user-attachments/assets/efeb4b96-cc78-4518-af83-7f41bf660cb6)

### Software Information

```text
~
```

**Comment by ayangweb** [comment]
你说的什么跟什么啊？截图说清楚

**Comment by David-design352** [comment]
抱歉没说清楚，具体是遇到了EcoPaste热键打开剪贴板窗口没有反应，无法退出程序（用资源管理器结束掉重启EcoPaste恢复了正常）

**Comment by David-design352** [comment]
> 奇怪了，我以为是偏好设置窗口打不开，后续你再遇到请给我详细的视频步骤🌹

伟大的开发者，经过不断尝试，我似乎找到了该问题的原因，是我在优化内存时会关闭WebView2管理器
![PixPin_2024-11-27_01-09-39](https://github.com/user-attachments/assets/e51e62c1-fd8a-4a92-a9c1-71480d0240ed)

**Comment by ayangweb** [comment]
原来如此，那就不奇怪了！

https://ecopaste.cn/problem/windows/start-failed#原因
