### ISSUE TITLE
[security bug] 在复制html的时候出现xss漏洞

### ISSUE THREAD

**Issue by Y4er** [EcoPasteHub/EcoPaste#843]
### Describe the bug

在复制html的时候出现xss漏洞

![image](https://github.com/user-attachments/assets/eb6ec1e9-7725-4be3-9a27-ea1e2d7e3fc9)

### Software Information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.4.0",
  "platform": "windows",
  "platformArch": "x86_64",
  "platformVersion": "10.0.19045"
}
```

**Comment by Y4er** [comment]
https://github.com/EcoPasteHub/EcoPaste/blob/7f9fafa5f24c62816fd450d962b55824154f3f9a/src/pages/Clipboard/Panel/components/List/components/Item/components/HTML/index.tsx#L38

**Comment by ayangweb** [comment]
OK，感谢提醒，需要对 html 的内容进行消毒处理！

**Comment by Y4er** [comment]
这样修复复制粘贴出来的内容会变吗？

**Comment by ayangweb** [comment]
不影响复制的，只是渲染时过滤！
