### ISSUE TITLE
[feat] 希望增加 不自动粘贴  选择

### ISSUE THREAD

**Issue by wilsonsui** [EcoPasteHub/EcoPaste#846]
### Describe the problem

选择了条目 不自动粘贴至光标处

### Describe the solution you'd like

选择了条目 不自动粘贴至光标处

**Comment by ayangweb** [comment]
是遇到了什么问题吗？

**Comment by wilsonsui** [comment]
你好 在某些情况下 选择了条目 不希望立即被粘贴至输入处  如果能增加不自动粘贴选项给与选择 最好不过了

**Comment by ayangweb** [comment]
<img width="730" alt="image" src="https://github.com/user-attachments/assets/846982f8-bc61-4168-a8bb-eb3c97627703">

把自动粘贴选择成双击！

**Comment by ayangweb** [comment]
长时间未得到回复，issue 先关了，有问题我再打开！
