### ISSUE TITLE
[feat] linux版本的libwebkit2gtk版本，能兼容更老的版本吗

### ISSUE THREAD

**Issue by WSure00** [EcoPasteHub/EcoPaste#847]
### Describe the problem

我试图安装软件，提示libwebkit2gtk 依赖。我尝试安装更新的版本，但是依赖太多了。影响系统的很多库
我的系统: ubuntu 20.04

 eco-paste : Depends: libwebkit2gtk-4.1-0 but it is not installable
 libgtk-3-dev : Depends: gir1.2-gtk-3.0 (= 3.24.18-1ubuntu1) but 3.24.20-0ubuntu1.1 is to be installed
                Depends: libatk-bridge2.0-dev but it is not going to be installed
                Depends: libatk1.0-dev (>= 2.15.1) but it is not going to be installed
                Depends: libegl1-mesa-dev but it is not going to be installed
                Depends: libepoxy-dev (>= 1.0) but it is not going to be installed
                Depends: libgdk-pixbuf2.0-dev (>= 2.40.0) but it is not going to be installed
                Depends: libwayland-dev (>= 1.9.91) but it is not going to be installed
                Depends: libxdamage-dev but it is not going to be installed
                Depends: libxinerama-dev but it is not going to be installed
                Depends: libxkbcommon-dev but it is not going to be installed
                Depends: wayland-protocols (>= 1.14) but it is not going to be installed
                Depends: libgtk-3-0 (= 3.24.18-1ubuntu1) but 3.24.20-0ubuntu1.1 is to be installed
 libwebkit2gtk-4.0-dev : Depends: gir1.2-webkit2-4.0 (= 2.28.1-1) but it is not going to be installed
                         Depends: libsoup2.4-dev (>= 2.40) but it is not going to be installed
                         Depends: libjavascriptcoregtk-4.0-dev (= 2.28.1-1) but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

### Describe the solution you'd like

希望能兼容更老的版本，感谢佬！

**Comment by witt-bit** [comment]
Ecopaste底层是tauri v2,先决条件是`webGTK >= libwebkit2gtk-4.0`,目前没有看到官方的支持

下面是一些tauri的讨论和官方的文档，你可以尝试找找其他人有没有解决方案

1.[tauriV2 Linux前置依赖项](https://v2.tauri.app/zh-cn/start/prerequisites/#linux)
2.[tauri issue ](https://github.com/tauri-apps/tauri/issues/9662)
3.[Tauri Debian软件包分发](https://v2.tauri.app/zh-cn/distribute/debian/#debian)

**Comment by ayangweb** [comment]
需要上游支持，那我先关闭 issue 了！
