### ISSUE TITLE
[bug] 从剪切板选择粘贴后，粘贴的文字会处于最上方

### ISSUE THREAD

**Issue by SammySnake-d** [EcoPasteHub/EcoPaste#848]
### Describe the bug

原本剪切板排序A,B,C,D，选中C粘贴后排序就变成了C，A，B，D,这种顺序的改变会让原本想要粘贴的内容发生移动，容易找不到要粘贴的内容是什么，特别当剪切板有重复的内容时，要找到粘贴的内容就更加困难

期望：能够不改变剪切板的顺序。这样一来当我想要按顺序粘贴某些内容时，我只需要记住我当时第一条复制到剪切板的内容大致是什么即可。

### Software Information

```text
版本：v0.40
```

### Additional context

另外，能否对剪切板的相同文本内容进行去重？

**Comment by ayangweb** [comment]
Duplicate of #642 

去重已经是支持了，你遇到了什么问题？

**Comment by SammySnake-d** [comment]
> Duplicate of #642
> 
> 去重已经是支持了，你遇到了什么问题？

您好，很抱歉我没有说明清楚，您已经支持了同类型的去重，但是不同类型的同内容的去重并没有支持。

也许是因为我初次使用的原因，当我跨软件来回复制粘贴时习惯性的对文本进行了复制，导致剪切板出现了相同的内容，但是文本类型不同。
您能优化这个因素吗

![image](https://github.com/user-attachments/assets/f9138a7a-ddae-4295-938c-e2cfb9ae1aca)

**Comment by ayangweb** [comment]
这并不是一个 Bug，也不会进行优化，因为它们属于不同的类型！

**Comment by ayangweb** [comment]
Duplicate of #642
