### ISSUE TITLE
[bug] macos Sequoia 15.1无法启动，显示"EcoPaste"已损坏，无法打开。

### ISSUE THREAD

**Issue by MatChaW886** [EcoPasteHub/EcoPaste#849]
### Describe the bug

通过home brew下载，正常安装后显示已损坏：

![image](https://github.com/user-attachments/assets/185dab41-1e76-4c32-bbc7-869a1e57a1f9)
![image](https://github.com/user-attachments/assets/5eb9ce9a-194f-4b6b-b808-9e1d13d6762a)

### Software Information

```text
Macbook m1pro
macos Sequoia 15.1
```

**Comment by ayangweb** [comment]
https://ecopaste.cn/problem/macos/damage
