### ISSUE TITLE
[feat] 能否用此应用取代系统的win+v剪贴板？

### ISSUE THREAD

**Issue by bakeham** [EcoPasteHub/EcoPaste#850]
### Describe the problem

我尝试配置快捷键win+v时，呼出的系统的剪贴板

### Describe the solution you'd like

希望能够支持拦截系统的win+v剪贴板

**Comment by ayangweb** [comment]
Win+V 快捷键需要通过快捷键转发实现，建议尝试使用微软官方产品： https://learn.microsoft.com/en-us/windows/powertoys/

**Comment by ayangweb** [comment]
目前该功能仅能通过转发实现。如果有人有更好地实现方案，欢迎提供建议或提交 PR。
