### ISSUE TITLE
[bug] 点击自动更新后无法完成更新

### ISSUE THREAD

**Issue by jeffhuien** [EcoPasteHub/EcoPaste#851]
### Describe the bug

点击自动更新后无法完成更新，进度条完成后会重启应用，但是重启完成后还是旧版本，而且会在弹一次更新弹窗
![image](https://github.com/user-attachments/assets/3eb36d1d-3cfe-42a9-a5ae-ff41386265c5)

### Software Information

```text
win11 pro
```

**Comment by ayangweb** [comment]
版本 0.2 到 0.4 存在不兼容更新，请务必完全卸载旧版软件及其数据后，重新安装最新版本。
