### ISSUE TITLE
[bug] 复制 bash 脚本，剪切板列表展示重叠问题

### ISSUE THREAD

**Issue by leinad59** [EcoPasteHub/EcoPaste#853]
### Describe the bug

当时从 https://ecopaste.cn/problem/macos/damage 页面复制
`sudo xattr -r -d com.apple.quarantine /Applications/EcoPaste.app` 
这行代码，查看列表发现的。

下图中，代码与下方的四个操作按钮重叠。

![image](https://github.com/user-attachments/assets/be5d43a8-490f-4d35-bffa-99414ed8a5db)

### Reproduction

无法复现

### Expected behavior

代码部分不被遮挡

### Software Information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.4.0",
  "platform": "macos",
  "platformArch": "aarch64",
  "platformVersion": "14.2.0"
}
```

**Comment by leinad59** [comment]
![image](https://github.com/user-attachments/assets/bf1fb778-a1be-40a8-bfc3-417e2fcb693d)

update: 这个位置好像还是有按钮的，鼠标悬浮有文案提示，但操作按钮不可见。是暗色模式的原因？

**Comment by leinad59** [comment]
夜间模式复制的，关闭夜间模式，白底白字，看不到内容 ↓

![image](https://github.com/user-attachments/assets/94d27012-89ae-4158-8783-4004aea94a2d)

**Comment by ayangweb** [comment]
> 夜间模式复制的，关闭夜间模式，白底白字，看不到内容 ↓

这个属于正常现象，复制的内容原模原样显示出来，不会做特殊处理！

**Comment by ayangweb** [comment]
> update: 这个位置好像还是有按钮的，鼠标悬浮有文案提示，但操作按钮不可见。是暗色模式的原因？

这个问题的原因在于，网站的功能主要通过 CSS 实现，显示和隐藏是依赖一些动态变量控制的。然而，当内容被复制后，只保留了 HTML 和 CSS，导致相关信息直接暴露。因此，鼠标移入时显示的效果会一并出现在复制的内容中。

**Comment by ayangweb** [comment]
所以这不算是 bug，复制代码一般都需要直接点击复制图标按钮进行复制，并不需要自己选择后复制！
