### ISSUE TITLE
[feat] 拖动不方便

### ISSUE THREAD

**Issue by jeffhuien** [EcoPasteHub/EcoPaste#855]
### Describe the problem

![image](https://github.com/user-attachments/assets/048da998-6bee-430e-836c-330987efed82)

### Describe the solution you'd like

如果可以的话， 工具栏与搜索框交换位置，  工具栏上增加margin 留出空白方便拖动

**Comment by ayangweb** [comment]
很多区域都是可拖动的！

https://github.com/user-attachments/assets/c3bd82d4-ac95-45a5-8883-f868f42aeb65

**Comment by jeffhuien** [comment]
图片上有，我知道


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月30日(周六) 下午4:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [EcoPasteHub/EcoPaste] [feat] 拖动不方便 (Issue #855)




 
很多区域都是可拖动的！
 
https://github.com/user-attachments/assets/c3bd82d4-ac95-45a5-8883-f868f42aeb65
 
&mdash;

**Comment by ayangweb** [comment]
OK，暂时不会对这块做拖动优化
