### ISSUE TITLE
[feat] 支持给复制项目设置热键

### ISSUE THREAD

**Issue by moreant** [EcoPasteHub/EcoPaste#856]
### Describe the problem

我是从 Ditto 转过来的，发现有个经常使用的功能在 EcoPaste 是没有的，希望可以支持。

就是在 Ditto 中，可以对复制的属性设置热键，在唤醒窗口出来后，再按下热键后就直接粘贴进输入框了。
这对于经常需要高频使用的复制内容是非常方便的，不用频繁的搜索和查找了，直接肌肉记忆。

![image](https://github.com/user-attachments/assets/0f2104ee-711b-4854-a19c-74fde47478c4)

### Describe the solution you'd like

感觉可以在这里加上类似的设置热键功能。
![image](https://github.com/user-attachments/assets/b7c64d83-21ae-474b-b835-be26032a026c)

**Comment by ayangweb** [comment]
Duplicate of #570
