### ISSUE TITLE
[bug] macOS 多屏幕环境下，剪贴板窗口无法跟随鼠标显示

### ISSUE THREAD

**Issue by skiina** [EcoPasteHub/EcoPaste#858]
### Describe the bug

macos 当切换桌面后快捷键失效，比如在桌面1快捷键有效，切换到桌面2后快捷键失效

### Software Information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.4.0",
  "platform": "macos",
  "platformArch": "x86_64",
  "platformVersion": "13.7.1"
}
```

**Comment by ayangweb** [comment]
录个完整的视频看看

**Comment by skiina** [comment]
现在又可以了，刚才是我在桌面1按快捷键，剪贴板出现在了桌面2然后又消失
等我再复现了录一个视频

**Comment by ayangweb** [comment]
开启这个选项试试呢！

<img width="730" alt="image" src="https://github.com/user-attachments/assets/d8d97059-968d-4470-8049-7fda9c456001">

**Comment by skiina** [comment]
刚刚复现了这个问题，录了一小段的视频，设置成跟随鼠标也不行
https://github.com/user-attachments/assets/3c24a889-8f3a-49f0-b4d4-b36a0847b9a1

**Comment by ayangweb** [comment]
你是扩展屏吗？

**Comment by skiina** [comment]
> 你是扩展屏吗？

是的，外接的显示器
电脑长时间睡眠之后肯定会出现这个问题

**Comment by ayangweb** [comment]
OK，这个问题前段时间群里面已经发现了，我们会进行优化的！

**Comment by ayangweb** [comment]
我修复了这个问题，但是需要你帮助测试一下，加入首页的微信群或者 QQ 群，帮忙测试一下吧！
