### ISSUE TITLE
[feat] 每一条issue加编码，另外显示的外框更小一些，间距小一些，以便显示更多

### ISSUE THREAD

**Issue by letterstar360** [EcoPasteHub/EcoPaste#860]
### Describe the problem

每一条issue加编码，另外显示的外框更小一些，间距小一些，以便显示更多

### Describe the solution you'd like

每一条issue加编码，另外显示的外框更小一些，间距小一些，以便显示更多

**Comment by ayangweb** [comment]
Duplicate of #271
