### ISSUE TITLE
[bug] 复制音效Bug

### ISSUE THREAD

**Issue by MangoBank** [EcoPasteHub/EcoPaste#864]
### Describe the bug

开启复制音效以后，未复制的情况下随机播放复制音效。有时候是单独一声，有时候连续多声。

### Software Information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.4.0",
  "platform": "macos",
  "platformArch": "aarch64",
  "platformVersion": "15.1.1"
}
```

**Comment by ayangweb** [comment]
你电脑有没有 PopClip 这款 app？

**Comment by MangoBank** [comment]
对的，我有这款软件。

**Comment by ayangweb** [comment]
把这个软件退掉，然后再观察一段时间

**Comment by MangoBank** [comment]
> 把这个软件退掉，然后再观察一段时间
好的，我试一下再反馈。

**Comment by ayangweb** [comment]
我电脑反正起初也遇到这个问题，我以为是上游库的 bug，然后经过测试，是这款软件莫名奇妙的一直在触发复制事件！

**Comment by MangoBank** [comment]
> 把这个软件退掉，然后再观察一段时间
关掉后确实好了，没有声音了，但PopClip是个关键软件。不知道能否修复？

**Comment by ayangweb** [comment]
正如我所说的，这是PopClip的问题，频繁触发复制事件的bug应该由他们来修复

**Comment by ayangweb** [comment]
<img width="1230" alt="image" src="https://github.com/user-attachments/assets/5fc1a1de-c205-49f3-8d9b-65f063f8ea32">

得到回信了，确实是 PopClip 主动触发的！
