### ISSUE TITLE
[bug] 暗黑模式Bug，无法看清复制的内容

### ISSUE THREAD

**Issue by MangoBank** [EcoPasteHub/EcoPaste#867]
### Describe the bug

如图所示
<img width="356" alt="Screenshot 2024-12-01 at 18 10 46" src="https://github.com/user-attachments/assets/6e49382a-9cbf-482a-ba7c-dcaf22d91850">
，在暗黑模式下，复制的文本显示也是黑色的，无法看清内容。

### Software Information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.4.0",
  "platform": "macos",
  "platformArch": "aarch64",
  "platformVersion": "15.1.1"
}
```

**Comment by ayangweb** [comment]
Duplicate of #https://github.com/EcoPasteHub/EcoPaste/issues/832#issuecomment-2495455858
