### ISSUE TITLE
[feat] 保持剪切板历史记录的有序性

### ISSUE THREAD

**Issue by doraemonkeys** [EcoPasteHub/EcoPaste#870]
### Describe the problem

希望EcoPaste添加一个功能增强。目前，从历史记录中复制剪贴板条目时，该条目会被移动到列表顶部。这会打乱原有顺序，使得查找相邻剪贴板条目变得困难。

### Describe the solution you'd like

请添加一个选项，以保持剪贴板历史的顺序。当用户从历史记录中复制条目时，不要将其移动到顶部。这样可以帮助用户轻松找到并比较相邻的剪贴板条目。

**Comment by ayangweb** [comment]
Duplicate of #642
