### ISSUE TITLE
[feat] 使用上的易用性改进

### ISSUE THREAD

**Issue by myderr** [EcoPasteHub/EcoPaste#872]
### Describe the problem

1、不能上下光标选择并且回车确定。
场景：全键盘的时候我会唤起面板，搜索内容，然后上下选择后确定。
2、弹出位置是没有跟随当前光标位置的功能。
场景同上
3、内容行高无法定义，或者不能动态。
场景：我有一些小文本，就一行高度，但是现在占用了很高的位置，我得搜索找内容了。

### Describe the solution you'd like

如上

**Comment by ayangweb** [comment]
1. 已经支持，不支持请录制带键盘按键的视频
2. 如图：
<img width="730" alt="image" src="https://github.com/user-attachments/assets/7ee17f49-735d-4b63-b379-ff5b56069796">
3. Duplicate of #271

**Comment by myderr** [comment]
> 1. 已经支持，不支持请录制带键盘按键的视频
> 2. 如图：
> 
> <img alt="image" width="730" src="https://private-user-images.githubusercontent.com/75017711/391433884-7ee17f49-735d-4b63-b379-ff5b56069796.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMjEzODksIm5iZiI6MTczMzEyMTA4OSwicGF0aCI6Ii83NTAxNzcxMS8zOTE0MzM4ODQtN2VlMTdmNDktNzM1ZC00YjYzLWIzNzktZmY1YjU2MDY5Nzk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDA2MzEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkNzI3ODIyNzNhZjU1NGM3MTdlNGQ2ZTdiNWUxNWE3ZjE0ZDk1NTQ0NDljMWIzNDk3OTgzNDEzYTY0MWMwNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._eBYhQ6WygGqrE6IU2rYMMnsNdhztw3zMMIJPvtWv74">
> 3. Duplicate of [[feat]: 紧凑模式或高度自适应模式 #271](https://github.com/EcoPasteHub/EcoPaste/issues/271)

好的，1没问题了
2的话我的意思是不是跟随鼠标移动，是跟随文本框光标
![image](https://github.com/user-attachments/assets/5c92954a-9491-4d59-8aab-5c48cbeb1b63)
就是我输入光标的位置和鼠标位置不是在同一个地方
可能有点抽象，全键盘表单录入的时候，我的输入光标是使用tab控制的

**Comment by ayangweb** [comment]
2. Duplicate of #264 目前来说，不打算支持！
3. 重复问题，等支持。
