### ISSUE TITLE
[bug] vs中双引号内的字符不能复制 

### ISSUE THREAD

**Issue by mccoymir** [EcoPasteHub/EcoPaste#873]
### Describe the bug

  vs2022中的c#代码
  return DbHelperSQL.ExecuteDataset(CommandType.StoredProcedure, "p_gz_GoldCardSalegroup_inntype", para).Tables[0];
  复制上面一行信息中的 p_gz_GoldCardSalegroup_inntype 不能复制 但是比如复制cedure, "p_gz_Go  就又可以
  重启软件后恢复了 比较奇怪的bug

### Software Information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.4.0",
  "platform": "windows",
  "platformArch": "x86_64",
  "platformVersion": "10.0.14393"
}
```

**Comment by ayangweb** [comment]
录视频说明！

**Comment by ayangweb** [comment]
长时间未得到回复，先关了！
