### ISSUE TITLE
[feat] 希望能增加类似PasteMate的复制内容进行自定义分类标签归纳功能。

### ISSUE THREAD

**Issue by wenkai158913488** [EcoPasteHub/EcoPaste#877]
### Describe the problem

希望能增加类似PasteMate的复制内容进行自定义分类标签归纳功能。功能交互参照PasteMate，有助于有很多类内容要复制时，不用搜索，直接点击分类标签即可快速找到。

### Describe the solution you'd like

希望能增加类似PasteMate的复制内容进行自定义分类标签归纳功能。功能交互参照PasteMate，有助于有很多类内容要复制时，不用搜索，直接点击分类标签即可快速找到。
可以参考如下截图。
![微信截图_20241205093533](https://github.com/user-attachments/assets/a1451a72-4624-4d80-b1b0-f5760fac14a2)

**Comment by ayangweb** [comment]
Duplicate of #145
