### ISSUE TITLE
[bug] 建议重复的内容做合并

### ISSUE THREAD

**Issue by xiaopenghust** [EcoPasteHub/EcoPaste#880]
### Describe the bug

建议重复的内容做合并
**
![image](https://github.com/user-attachments/assets/1e5f1b6d-a5b1-4ccd-9108-5a065df5aaf8)
**

### Software Information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.4.0",
  "platform": "windows",
  "platformArch": "x86_64",
  "platformVersion": "10.0.22621"
}
```

**Comment by ayangweb** [comment]
录一个能复现的视频，相同数据是已经做过去重处理的！
