### ISSUE TITLE
[feat] 每条复制内容显示高度台固定，希望能动态调整

### ISSUE THREAD

**Issue by Zolliner** [EcoPasteHub/EcoPaste#881]
### Describe the problem

由于高度固定，大片空白看着并不美观，也不方便滑动查找

![图片](https://github.com/user-attachments/assets/e13c7e28-e736-4300-8777-9fffb6aac230)

### Describe the solution you'd like

希望可以借鉴下pastebar的样式，压缩一下无用的空白
![图片](https://github.com/user-attachments/assets/86d4f95b-c191-4580-a22c-2187c5b27ddb)

**Comment by ayangweb** [comment]
Duplicate of #271
