### ISSUE TITLE
[bug] 调出ecopaste的剪贴板预览小窗之后，用Rime输入法搜索剪贴板，界面会卡住

### ISSUE THREAD

**Issue by GRDpengyuyan** [EcoPasteHub/EcoPaste#882]
### Describe the bug

简单讲就是无法使用rime输入法在小窗界面的搜索框里实现输入，目前不确定是rime的锅还是ecopaste的锅，先在这里反馈一下。
![Snipaste_2024-12-05_21-38-03](https://github.com/user-attachments/assets/cabde172-5558-42f8-94a5-c13940afee10)

### Software Information

```text
win11 家庭中文 23H2，EcoPaste V0.4.0，Rime输入法 0.16.3（使用白霜词库, https://github.com/gaboolic/rime-frost)
```

**Comment by GRDpengyuyan** [comment]
对了，卡住之后，只需要找到右下角任务栏的ecopaste图标，在图标上右击一下，就可以恢复使用了

**Comment by ayangweb** [comment]
Duplicate of https://github.com/EcoPasteHub/EcoPaste/issues/524#issuecomment-2364127743
