### ISSUE TITLE
[bug] 导出文件问题

### ISSUE THREAD

**Issue by witt-bit** [EcoPasteHub/EcoPaste#886]
### Describe the bug

1.鼠标右键就隐藏剪贴板窗口了
2.导出html，会用浏览器打开html文件(我确实html默认打开方式是Chrome)

https://github.com/user-attachments/assets/93583687-f1a5-41f8-8ef6-1bcbaa5f55b2

### Software Information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.5.0-beta.1",
  "tauriVersion": "2.1.1",
  "platform": "linux",
  "platformArch": "x86_64",
  "platformVersion": "24.2.0"
}
```

**Comment by witt-bit** [comment]
![eec775d62254c8f9c7ee9299d74497b1](https://github.com/user-attachments/assets/551d73bf-0b0e-45a5-a98c-39edddaa923e)

**Comment by ayangweb** [comment]
1 去 tauri 的 issue 找解决访问
2 我给你截图就是解决方案
