### ISSUE TITLE
[bug] Linux回到顶部失效

### ISSUE THREAD

**Issue by witt-bit** [EcoPasteHub/EcoPaste#889]
### Describe the bug

1.回到顶部失效
2.鼠标滚轮在点击回到顶部后，会先闪烁到顶部，才开始滚动

https://github.com/user-attachments/assets/4844c4f2-707f-4225-bc96-78a73b9e35dd

### Software Information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.5.0-beta.1",
  "tauriVersion": "2.1.1",
  "platform": "linux",
  "platformArch": "x86_64",
  "platformVersion": "24.2.0"
}
```

**Comment by ayangweb** [comment]
v0.5.0-beta.2 你试下！

**Comment by witt-bit** [comment]
v0.5.0-beta.2已修复   很丝滑

**Comment by ayangweb** [comment]
我猜也是 tauri 日志插件搞得鬼
