### ISSUE TITLE
[feat] 

### ISSUE THREAD

**Issue by xcvg661** [EcoPasteHub/EcoPaste#891]
### Describe the problem

1、希望能增加一个剪贴板编辑功能（可能有时候需要对复制的代码进行编辑后粘贴，否则还需要进其他输入框编一遍再粘贴）2、然后收藏增加分组（对不同的常用内容进行输入）。

### Describe the solution you'd like

1、希望能增加一个剪贴板编辑功能（可能有时候需要对复制的代码进行编辑后粘贴，否则还需要进其他输入框编一遍再粘贴）2、然后收藏增加分组（对不同的常用内容进行输入）。

**Comment by ayangweb** [comment]
1. Duplicate of #324 
2. Duplicate of #145
