### ISSUE TITLE
[feat] 新增配置项-备注后可自动收藏

### ISSUE THREAD

**Issue by ChiefChina** [EcoPasteHub/EcoPaste#896]
### Describe the problem

对于常用的内容我会设置备注，但是现在的删除逻辑是讲未收藏的全部删了（含已经添加备注的内容）；
建议新增配置项，能够自动收藏有备注的内容；
自动收藏后，如果取消收藏则按照之前规则统一删除，如果修改备注则再次自动收藏；

### Describe the solution you'd like

对于常用的内容我会设置备注，但是现在的删除逻辑是讲未收藏的全部删了（含已经添加备注的内容）；
建议新增配置项，能够自动收藏有备注的内容；
自动收藏后，如果取消收藏则按照之前规则统一删除，如果修改备注则再次自动收藏；

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Implemented auto-favorite feature for clipboard items with notes. Added a new configuration option in the clipboard settings and updated the item deletion logic.

You can review changes in this commit: https://github.com/mnmnk43434/EcoPasteHub-EcoPaste-896/commit/35a1657238efb8ab65cd08daece04d2bd86f2da2.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
