### ISSUE TITLE
[feat] 剪贴板 收藏的内容删除时增加限制

### ISSUE THREAD

**Issue by zhumengdefeng** [EcoPasteHub/EcoPaste#900]
### Describe the problem

收藏的内容删除时没有提示，手快的时候就直接删除了

### Describe the solution you'd like

希望收藏的内容删除时增加提示

### Alternatives considered

无

### Additional context

无

**Comment by ayangweb** [comment]
好的，后续会加入可配置项来决定是否开启删除提示！
