### ISSUE TITLE
[bug] 稳定性太差了

### ISSUE THREAD

**Issue by congSjwbsz** [EcoPasteHub/EcoPaste#904]
### Describe the bug

删除全部历史记录时候一直卡住，其次的话我的收藏那里不是丢失图片就是丢失文字，已经不是一次两次的事了，先加强下稳定性吧

### Reproduction

删除全部历史记录时候一直卡住，其次的话我的收藏那里不是丢失图片就是丢失文字，已经不是一次两次的事了，先加强下稳定性吧

### Expected behavior

删除全部历史记录时候一直卡住，其次的话我的收藏那里不是丢失图片就是丢失文字，已经不是一次两次的事了，先加强下稳定性吧

### Software Information

```text
删除全部历史记录时候一直卡住，其次的话我的收藏那里不是丢失图片就是丢失文字，已经不是一次两次的事了，先加强下稳定性吧
```

**Comment by ayangweb** [comment]
<img width="863" alt="image" src="https://github.com/user-attachments/assets/a8002105-3d38-4848-8c03-6b5370265747" />

都不会认真填日志？别人都稳定着，就你不稳定，有没有想过是你的问题？

**Comment by ayangweb** [comment]
从哪个版本升级到的哪个版本？日志呢？啥都不发，光叭叭。

**Comment by congSjwbsz** [comment]
[EcoPaste.log](https://github.com/user-attachments/files/18161083/EcoPaste.log)

**Comment by congSjwbsz** [comment]
{
  "appName": "EcoPaste",
  "appVersion": "0.4.0",
  "platform": "windows",
  "platformArch": "x86_64",
  "platformVersion": "10.0.19045"
}

**Comment by ayangweb** [comment]
完全卸载重装再反馈。

**Comment by ayangweb** [comment]
下载最新的测试了没？现在是什么情况？

**Comment by ayangweb** [comment]
长时间未收到回复，暂时关闭 issue，如有问题可随时重新开启。
