### ISSUE TITLE
[feat] 请添加剪贴板文本复制来源的功能

### ISSUE THREAD

**Issue by HildaJ** [EcoPasteHub/EcoPaste#905]
### Describe the problem

作者您好，我是从Clipdiary转移到Ecopaste v0.4.0的用户，请问能否和Clipdairy一样增加一个功能显示复制文本来源的窗口？

### Describe the solution you'd like

不仅记录了粘贴的文本/图片，还可以同时记录粘贴文本/图片来自哪个应用（如图）。如果是从浏览器里复制的，还能同时记录来源的网址是哪里的。
![2yon4vB](https://github.com/user-attachments/assets/d072062b-d46d-4106-bb5a-2317b7e73e71)

**Comment by ayangweb** [comment]
Duplicate of #837 

重复问题，会关闭

有的，等待后续支持！
