### ISSUE TITLE
可否增加返回顶部功能和拖拽粘贴功能

### ISSUE THREAD

**Issue by xiaomage-023** [EcoPasteHub/EcoPaste#909]
1.可否增加返回顶部功能，下拉翻看历史记录，查看最新复制内容需要迅速返回顶部。
2.可否增加拖拽的粘贴功能

**Comment by ayangweb** [comment]
你用的啥版本？

**Comment by ayangweb** [comment]
最新版已经支持了这两个功能！

**Comment by xiaomage-023** [comment]
0.4.0版本，返回顶部功能看到了，拖拽不了文本到wps里
![剪贴板图片 (10)](https://github.com/user-attachments/assets/5f31a825-94e1-45cb-bc32-077ed8e313d9)

**Comment by ayangweb** [comment]
未来会支持，目前上游插件有 bug
