### ISSUE TITLE
[feat] 希望能够给收藏的条目添加标签或者分类

### ISSUE THREAD

**Issue by Brioal** [EcoPasteHub/EcoPaste#913]
### 描述问题

如果能给收藏的内容添加标签或者分类将会更方便的管理收藏的内容，有点类似mac上的Paste应用
![image](https://github.com/user-attachments/assets/0d271193-d5a9-4efe-8d4a-0504c9ae54ec)

### 描述您希望的解决方案

希望能够给收藏条目分类或者添加标签

### 附加信息

可以参考Mac上的Paste应用

**Comment by ayangweb** [comment]
Duplicate of #145
