### ISSUE TITLE
[feat] 记忆窗口尺寸；允许最大化

### ISSUE THREAD

**Issue by ciddiaz** [EcoPasteHub/EcoPaste#914]
### 描述问题

个人觉得现在的剪贴板窗口有些小，若经常需要调用之前的剪切、复制内容需要经常滚动而不方便；虽然可以手动拖动窗口轮廓，下次重启电脑又把尺寸改回去了，又得重拖

### 描述您希望的解决方案

希望在剪贴板窗口标题栏右端增加最大化按钮，同时像记忆窗口位置一样，记忆窗口尺寸或是否最大化状态

**Comment by ayangweb** [comment]
窗口记忆早就支持了，有问题发错误报告，最大化不会考虑！
