### ISSUE TITLE
[bug] 在macos catalina（10.15.x）上UI显示错乱

### ISSUE THREAD

**Issue by dengzha0** [EcoPasteHub/EcoPaste#918]
### 描述 Bug

直接看截图，应该很明显了。
![1](https://github.com/user-attachments/assets/48981243-1531-4d81-b5a2-e86db8895c46)

![2](https://github.com/user-attachments/assets/80274372-7288-459a-a538-829c18b71fb3)

### 软件信息

```text
macos 10.15.7
```

**Comment by ayangweb** [comment]
[flex](https://developer.mozilla.org/zh-CN/docs/Web/CSS/flex) 布局不兼容当前旧版本系统，建议升级系统或使用其它 app。
