### ISSUE TITLE
[feat] 希望添加自定义分组的功能

### ISSUE THREAD

**Issue by Gwyn-S** [EcoPasteHub/EcoPaste#919]
### 描述问题

目前只有文本，文件，收藏几个分组，在我想更细致的分类时就做不到了，比如全是代码的时候，我可以建一个代码块的分组这样的

### 描述您希望的解决方案

可以加个由用户添加并重命名分组的功能吗，感谢

**Comment by ayangweb** [comment]
Duplicate of #145
